// Code generated by ent, DO NOT EDIT.

package usageupstreamattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usageupstreamattempt type in the database.
	Label = "usage_upstream_attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAttemptNo holds the string denoting the attempt_no field in the database.
	FieldAttemptNo = "attempt_no"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldServiceTier holds the string denoting the service_tier field in the database.
	FieldServiceTier = "service_tier"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldCacheCreation5mTokens holds the string denoting the cache_creation_5m_tokens field in the database.
	FieldCacheCreation5mTokens = "cache_creation_5m_tokens"
	// FieldCacheCreation1hTokens holds the string denoting the cache_creation_1h_tokens field in the database.
	FieldCacheCreation1hTokens = "cache_creation_1h_tokens"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldImageCount holds the string denoting the image_count field in the database.
	FieldImageCount = "image_count"
	// FieldVideoSeconds holds the string denoting the video_seconds field in the database.
	FieldVideoSeconds = "video_seconds"
	// FieldUpstreamCostMultiplier holds the string denoting the upstream_cost_multiplier field in the database.
	FieldUpstreamCostMultiplier = "upstream_cost_multiplier"
	// FieldUpstreamMultiplierChangeID holds the string denoting the upstream_multiplier_change_id field in the database.
	FieldUpstreamMultiplierChangeID = "upstream_multiplier_change_id"
	// FieldUpstreamMultiplierSource holds the string denoting the upstream_multiplier_source field in the database.
	FieldUpstreamMultiplierSource = "upstream_multiplier_source"
	// FieldUpstreamMultiplierEffectiveAt holds the string denoting the upstream_multiplier_effective_at field in the database.
	FieldUpstreamMultiplierEffectiveAt = "upstream_multiplier_effective_at"
	// FieldAccountFinanceProfileID holds the string denoting the account_finance_profile_id field in the database.
	FieldAccountFinanceProfileID = "account_finance_profile_id"
	// FieldBillable holds the string denoting the billable field in the database.
	FieldBillable = "billable"
	// FieldBillingObservedAt holds the string denoting the billing_observed_at field in the database.
	FieldBillingObservedAt = "billing_observed_at"
	// FieldUpstreamActualCharge holds the string denoting the upstream_actual_charge field in the database.
	FieldUpstreamActualCharge = "upstream_actual_charge"
	// FieldUpstreamActualChargeUsd holds the string denoting the upstream_actual_charge_usd field in the database.
	FieldUpstreamActualChargeUsd = "upstream_actual_charge_usd"
	// FieldUpstreamStandardCharge holds the string denoting the upstream_standard_charge field in the database.
	FieldUpstreamStandardCharge = "upstream_standard_charge"
	// FieldUpstreamChargeCurrency holds the string denoting the upstream_charge_currency field in the database.
	FieldUpstreamChargeCurrency = "upstream_charge_currency"
	// FieldUpstreamChargeUnitSemantics holds the string denoting the upstream_charge_unit_semantics field in the database.
	FieldUpstreamChargeUnitSemantics = "upstream_charge_unit_semantics"
	// FieldUpstreamBillingRequestID holds the string denoting the upstream_billing_request_id field in the database.
	FieldUpstreamBillingRequestID = "upstream_billing_request_id"
	// FieldUpstreamChargeSnapshot holds the string denoting the upstream_charge_snapshot field in the database.
	FieldUpstreamChargeSnapshot = "upstream_charge_snapshot"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the usageupstreamattempt in the database.
	Table = "usage_upstream_attempts"
)

// Columns holds all SQL columns for usageupstreamattempt fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldRequestID,
	FieldAttemptNo,
	FieldAccountID,
	FieldChannelID,
	FieldUpstreamModel,
	FieldServiceTier,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCacheReadTokens,
	FieldCacheCreationTokens,
	FieldCacheCreation5mTokens,
	FieldCacheCreation1hTokens,
	FieldRequestCount,
	FieldImageCount,
	FieldVideoSeconds,
	FieldUpstreamCostMultiplier,
	FieldUpstreamMultiplierChangeID,
	FieldUpstreamMultiplierSource,
	FieldUpstreamMultiplierEffectiveAt,
	FieldAccountFinanceProfileID,
	FieldBillable,
	FieldBillingObservedAt,
	FieldUpstreamActualCharge,
	FieldUpstreamActualChargeUsd,
	FieldUpstreamStandardCharge,
	FieldUpstreamChargeCurrency,
	FieldUpstreamChargeUnitSemantics,
	FieldUpstreamBillingRequestID,
	FieldUpstreamChargeSnapshot,
	FieldCompletedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// AttemptNoValidator is a validator for the "attempt_no" field. It is called by the builders before save.
	AttemptNoValidator func(int) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// ServiceTierValidator is a validator for the "service_tier" field. It is called by the builders before save.
	ServiceTierValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	InputTokensValidator func(int64) error
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	OutputTokensValidator func(int64) error
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// CacheReadTokensValidator is a validator for the "cache_read_tokens" field. It is called by the builders before save.
	CacheReadTokensValidator func(int64) error
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int64
	// CacheCreationTokensValidator is a validator for the "cache_creation_tokens" field. It is called by the builders before save.
	CacheCreationTokensValidator func(int64) error
	// DefaultCacheCreation5mTokens holds the default value on creation for the "cache_creation_5m_tokens" field.
	DefaultCacheCreation5mTokens int64
	// CacheCreation5mTokensValidator is a validator for the "cache_creation_5m_tokens" field. It is called by the builders before save.
	CacheCreation5mTokensValidator func(int64) error
	// DefaultCacheCreation1hTokens holds the default value on creation for the "cache_creation_1h_tokens" field.
	DefaultCacheCreation1hTokens int64
	// CacheCreation1hTokensValidator is a validator for the "cache_creation_1h_tokens" field. It is called by the builders before save.
	CacheCreation1hTokensValidator func(int64) error
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int64
	// RequestCountValidator is a validator for the "request_count" field. It is called by the builders before save.
	RequestCountValidator func(int64) error
	// DefaultImageCount holds the default value on creation for the "image_count" field.
	DefaultImageCount int64
	// ImageCountValidator is a validator for the "image_count" field. It is called by the builders before save.
	ImageCountValidator func(int64) error
	// DefaultVideoSeconds holds the default value on creation for the "video_seconds" field.
	DefaultVideoSeconds int64
	// VideoSecondsValidator is a validator for the "video_seconds" field. It is called by the builders before save.
	VideoSecondsValidator func(int64) error
	// UpstreamMultiplierSourceValidator is a validator for the "upstream_multiplier_source" field. It is called by the builders before save.
	UpstreamMultiplierSourceValidator func(string) error
	// DefaultBillable holds the default value on creation for the "billable" field.
	DefaultBillable bool
	// UpstreamChargeCurrencyValidator is a validator for the "upstream_charge_currency" field. It is called by the builders before save.
	UpstreamChargeCurrencyValidator func(string) error
	// UpstreamChargeUnitSemanticsValidator is a validator for the "upstream_charge_unit_semantics" field. It is called by the builders before save.
	UpstreamChargeUnitSemanticsValidator func(string) error
	// UpstreamBillingRequestIDValidator is a validator for the "upstream_billing_request_id" field. It is called by the builders before save.
	UpstreamBillingRequestIDValidator func(string) error
	// DefaultCompletedAt holds the default value on creation for the "completed_at" field.
	DefaultCompletedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageUpstreamAttempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAttemptNo orders the results by the attempt_no field.
func ByAttemptNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptNo, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByServiceTier orders the results by the service_tier field.
func ByServiceTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceTier, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByCacheCreation5mTokens orders the results by the cache_creation_5m_tokens field.
func ByCacheCreation5mTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreation5mTokens, opts...).ToFunc()
}

// ByCacheCreation1hTokens orders the results by the cache_creation_1h_tokens field.
func ByCacheCreation1hTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreation1hTokens, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByImageCount orders the results by the image_count field.
func ByImageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageCount, opts...).ToFunc()
}

// ByVideoSeconds orders the results by the video_seconds field.
func ByVideoSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVideoSeconds, opts...).ToFunc()
}

// ByUpstreamCostMultiplier orders the results by the upstream_cost_multiplier field.
func ByUpstreamCostMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamCostMultiplier, opts...).ToFunc()
}

// ByUpstreamMultiplierChangeID orders the results by the upstream_multiplier_change_id field.
func ByUpstreamMultiplierChangeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamMultiplierChangeID, opts...).ToFunc()
}

// ByUpstreamMultiplierSource orders the results by the upstream_multiplier_source field.
func ByUpstreamMultiplierSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamMultiplierSource, opts...).ToFunc()
}

// ByUpstreamMultiplierEffectiveAt orders the results by the upstream_multiplier_effective_at field.
func ByUpstreamMultiplierEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamMultiplierEffectiveAt, opts...).ToFunc()
}

// ByAccountFinanceProfileID orders the results by the account_finance_profile_id field.
func ByAccountFinanceProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountFinanceProfileID, opts...).ToFunc()
}

// ByBillable orders the results by the billable field.
func ByBillable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillable, opts...).ToFunc()
}

// ByBillingObservedAt orders the results by the billing_observed_at field.
func ByBillingObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingObservedAt, opts...).ToFunc()
}

// ByUpstreamActualCharge orders the results by the upstream_actual_charge field.
func ByUpstreamActualCharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamActualCharge, opts...).ToFunc()
}

// ByUpstreamActualChargeUsd orders the results by the upstream_actual_charge_usd field.
func ByUpstreamActualChargeUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamActualChargeUsd, opts...).ToFunc()
}

// ByUpstreamStandardCharge orders the results by the upstream_standard_charge field.
func ByUpstreamStandardCharge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStandardCharge, opts...).ToFunc()
}

// ByUpstreamChargeCurrency orders the results by the upstream_charge_currency field.
func ByUpstreamChargeCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamChargeCurrency, opts...).ToFunc()
}

// ByUpstreamChargeUnitSemantics orders the results by the upstream_charge_unit_semantics field.
func ByUpstreamChargeUnitSemantics(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamChargeUnitSemantics, opts...).ToFunc()
}

// ByUpstreamBillingRequestID orders the results by the upstream_billing_request_id field.
func ByUpstreamBillingRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamBillingRequestID, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
