// Code generated by ent, DO NOT EDIT.

package usageupstreamattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldRequestID, v))
}

// AttemptNo applies equality check predicate on the "attempt_no" field. It's identical to AttemptNoEQ.
func AttemptNo(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAttemptNo, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAccountID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldChannelID, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamModel, v))
}

// ServiceTier applies equality check predicate on the "service_tier" field. It's identical to ServiceTierEQ.
func ServiceTier(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldServiceTier, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreation5mTokens applies equality check predicate on the "cache_creation_5m_tokens" field. It's identical to CacheCreation5mTokensEQ.
func CacheCreation5mTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation1hTokens applies equality check predicate on the "cache_creation_1h_tokens" field. It's identical to CacheCreation1hTokensEQ.
func CacheCreation1hTokens(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreation1hTokens, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldRequestCount, v))
}

// ImageCount applies equality check predicate on the "image_count" field. It's identical to ImageCountEQ.
func ImageCount(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldImageCount, v))
}

// VideoSeconds applies equality check predicate on the "video_seconds" field. It's identical to VideoSecondsEQ.
func VideoSeconds(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldVideoSeconds, v))
}

// UpstreamCostMultiplier applies equality check predicate on the "upstream_cost_multiplier" field. It's identical to UpstreamCostMultiplierEQ.
func UpstreamCostMultiplier(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamCostMultiplier, v))
}

// UpstreamMultiplierChangeID applies equality check predicate on the "upstream_multiplier_change_id" field. It's identical to UpstreamMultiplierChangeIDEQ.
func UpstreamMultiplierChangeID(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierSource applies equality check predicate on the "upstream_multiplier_source" field. It's identical to UpstreamMultiplierSourceEQ.
func UpstreamMultiplierSource(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierEffectiveAt applies equality check predicate on the "upstream_multiplier_effective_at" field. It's identical to UpstreamMultiplierEffectiveAtEQ.
func UpstreamMultiplierEffectiveAt(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierEffectiveAt, v))
}

// AccountFinanceProfileID applies equality check predicate on the "account_finance_profile_id" field. It's identical to AccountFinanceProfileIDEQ.
func AccountFinanceProfileID(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAccountFinanceProfileID, v))
}

// Billable applies equality check predicate on the "billable" field. It's identical to BillableEQ.
func Billable(v bool) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldBillable, v))
}

// BillingObservedAt applies equality check predicate on the "billing_observed_at" field. It's identical to BillingObservedAtEQ.
func BillingObservedAt(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldBillingObservedAt, v))
}

// UpstreamActualCharge applies equality check predicate on the "upstream_actual_charge" field. It's identical to UpstreamActualChargeEQ.
func UpstreamActualCharge(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeUsd applies equality check predicate on the "upstream_actual_charge_usd" field. It's identical to UpstreamActualChargeUsdEQ.
func UpstreamActualChargeUsd(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamActualChargeUsd, v))
}

// UpstreamStandardCharge applies equality check predicate on the "upstream_standard_charge" field. It's identical to UpstreamStandardChargeEQ.
func UpstreamStandardCharge(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamStandardCharge, v))
}

// UpstreamChargeCurrency applies equality check predicate on the "upstream_charge_currency" field. It's identical to UpstreamChargeCurrencyEQ.
func UpstreamChargeCurrency(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeUnitSemantics applies equality check predicate on the "upstream_charge_unit_semantics" field. It's identical to UpstreamChargeUnitSemanticsEQ.
func UpstreamChargeUnitSemantics(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamBillingRequestID applies equality check predicate on the "upstream_billing_request_id" field. It's identical to UpstreamBillingRequestIDEQ.
func UpstreamBillingRequestID(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamBillingRequestID, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUsageLogID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldRequestID, v))
}

// AttemptNoEQ applies the EQ predicate on the "attempt_no" field.
func AttemptNoEQ(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAttemptNo, v))
}

// AttemptNoNEQ applies the NEQ predicate on the "attempt_no" field.
func AttemptNoNEQ(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldAttemptNo, v))
}

// AttemptNoIn applies the In predicate on the "attempt_no" field.
func AttemptNoIn(vs ...int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldAttemptNo, vs...))
}

// AttemptNoNotIn applies the NotIn predicate on the "attempt_no" field.
func AttemptNoNotIn(vs ...int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldAttemptNo, vs...))
}

// AttemptNoGT applies the GT predicate on the "attempt_no" field.
func AttemptNoGT(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldAttemptNo, v))
}

// AttemptNoGTE applies the GTE predicate on the "attempt_no" field.
func AttemptNoGTE(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldAttemptNo, v))
}

// AttemptNoLT applies the LT predicate on the "attempt_no" field.
func AttemptNoLT(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldAttemptNo, v))
}

// AttemptNoLTE applies the LTE predicate on the "attempt_no" field.
func AttemptNoLTE(v int) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldAttemptNo, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldAccountID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldChannelID))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// ServiceTierEQ applies the EQ predicate on the "service_tier" field.
func ServiceTierEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldServiceTier, v))
}

// ServiceTierNEQ applies the NEQ predicate on the "service_tier" field.
func ServiceTierNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldServiceTier, v))
}

// ServiceTierIn applies the In predicate on the "service_tier" field.
func ServiceTierIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldServiceTier, vs...))
}

// ServiceTierNotIn applies the NotIn predicate on the "service_tier" field.
func ServiceTierNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldServiceTier, vs...))
}

// ServiceTierGT applies the GT predicate on the "service_tier" field.
func ServiceTierGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldServiceTier, v))
}

// ServiceTierGTE applies the GTE predicate on the "service_tier" field.
func ServiceTierGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldServiceTier, v))
}

// ServiceTierLT applies the LT predicate on the "service_tier" field.
func ServiceTierLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldServiceTier, v))
}

// ServiceTierLTE applies the LTE predicate on the "service_tier" field.
func ServiceTierLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldServiceTier, v))
}

// ServiceTierContains applies the Contains predicate on the "service_tier" field.
func ServiceTierContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldServiceTier, v))
}

// ServiceTierHasPrefix applies the HasPrefix predicate on the "service_tier" field.
func ServiceTierHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldServiceTier, v))
}

// ServiceTierHasSuffix applies the HasSuffix predicate on the "service_tier" field.
func ServiceTierHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldServiceTier, v))
}

// ServiceTierIsNil applies the IsNil predicate on the "service_tier" field.
func ServiceTierIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldServiceTier))
}

// ServiceTierNotNil applies the NotNil predicate on the "service_tier" field.
func ServiceTierNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldServiceTier))
}

// ServiceTierEqualFold applies the EqualFold predicate on the "service_tier" field.
func ServiceTierEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldServiceTier, v))
}

// ServiceTierContainsFold applies the ContainsFold predicate on the "service_tier" field.
func ServiceTierContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldServiceTier, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCacheReadTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheCreation5mTokensEQ applies the EQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensNEQ applies the NEQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensIn applies the In predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCacheCreation5mTokens, vs...))
}

// CacheCreation5mTokensNotIn applies the NotIn predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCacheCreation5mTokens, vs...))
}

// CacheCreation5mTokensGT applies the GT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensGTE applies the GTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensLT applies the LT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensLTE applies the LTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCacheCreation5mTokens, v))
}

// CacheCreation1hTokensEQ applies the EQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensNEQ applies the NEQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensIn applies the In predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCacheCreation1hTokens, vs...))
}

// CacheCreation1hTokensNotIn applies the NotIn predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCacheCreation1hTokens, vs...))
}

// CacheCreation1hTokensGT applies the GT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensGTE applies the GTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensLT applies the LT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensLTE applies the LTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCacheCreation1hTokens, v))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldRequestCount, v))
}

// ImageCountEQ applies the EQ predicate on the "image_count" field.
func ImageCountEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldImageCount, v))
}

// ImageCountNEQ applies the NEQ predicate on the "image_count" field.
func ImageCountNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldImageCount, v))
}

// ImageCountIn applies the In predicate on the "image_count" field.
func ImageCountIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldImageCount, vs...))
}

// ImageCountNotIn applies the NotIn predicate on the "image_count" field.
func ImageCountNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldImageCount, vs...))
}

// ImageCountGT applies the GT predicate on the "image_count" field.
func ImageCountGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldImageCount, v))
}

// ImageCountGTE applies the GTE predicate on the "image_count" field.
func ImageCountGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldImageCount, v))
}

// ImageCountLT applies the LT predicate on the "image_count" field.
func ImageCountLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldImageCount, v))
}

// ImageCountLTE applies the LTE predicate on the "image_count" field.
func ImageCountLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldImageCount, v))
}

// VideoSecondsEQ applies the EQ predicate on the "video_seconds" field.
func VideoSecondsEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldVideoSeconds, v))
}

// VideoSecondsNEQ applies the NEQ predicate on the "video_seconds" field.
func VideoSecondsNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldVideoSeconds, v))
}

// VideoSecondsIn applies the In predicate on the "video_seconds" field.
func VideoSecondsIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldVideoSeconds, vs...))
}

// VideoSecondsNotIn applies the NotIn predicate on the "video_seconds" field.
func VideoSecondsNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldVideoSeconds, vs...))
}

// VideoSecondsGT applies the GT predicate on the "video_seconds" field.
func VideoSecondsGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldVideoSeconds, v))
}

// VideoSecondsGTE applies the GTE predicate on the "video_seconds" field.
func VideoSecondsGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldVideoSeconds, v))
}

// VideoSecondsLT applies the LT predicate on the "video_seconds" field.
func VideoSecondsLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldVideoSeconds, v))
}

// VideoSecondsLTE applies the LTE predicate on the "video_seconds" field.
func VideoSecondsLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldVideoSeconds, v))
}

// UpstreamCostMultiplierEQ applies the EQ predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierNEQ applies the NEQ predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierNEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierIn applies the In predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamCostMultiplier, vs...))
}

// UpstreamCostMultiplierNotIn applies the NotIn predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierNotIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamCostMultiplier, vs...))
}

// UpstreamCostMultiplierGT applies the GT predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierGT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierGTE applies the GTE predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierGTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierLT applies the LT predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierLT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierLTE applies the LTE predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierLTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamCostMultiplier, v))
}

// UpstreamCostMultiplierIsNil applies the IsNil predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamCostMultiplier))
}

// UpstreamCostMultiplierNotNil applies the NotNil predicate on the "upstream_cost_multiplier" field.
func UpstreamCostMultiplierNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamCostMultiplier))
}

// UpstreamMultiplierChangeIDEQ applies the EQ predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDNEQ applies the NEQ predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDIn applies the In predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamMultiplierChangeID, vs...))
}

// UpstreamMultiplierChangeIDNotIn applies the NotIn predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamMultiplierChangeID, vs...))
}

// UpstreamMultiplierChangeIDGT applies the GT predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDGTE applies the GTE predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDLT applies the LT predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDLTE applies the LTE predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamMultiplierChangeID, v))
}

// UpstreamMultiplierChangeIDIsNil applies the IsNil predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamMultiplierChangeID))
}

// UpstreamMultiplierChangeIDNotNil applies the NotNil predicate on the "upstream_multiplier_change_id" field.
func UpstreamMultiplierChangeIDNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamMultiplierChangeID))
}

// UpstreamMultiplierSourceEQ applies the EQ predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceNEQ applies the NEQ predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceIn applies the In predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamMultiplierSource, vs...))
}

// UpstreamMultiplierSourceNotIn applies the NotIn predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamMultiplierSource, vs...))
}

// UpstreamMultiplierSourceGT applies the GT predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceGTE applies the GTE predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceLT applies the LT predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceLTE applies the LTE predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceContains applies the Contains predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceHasPrefix applies the HasPrefix predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceHasSuffix applies the HasSuffix predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceIsNil applies the IsNil predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamMultiplierSource))
}

// UpstreamMultiplierSourceNotNil applies the NotNil predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamMultiplierSource))
}

// UpstreamMultiplierSourceEqualFold applies the EqualFold predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierSourceContainsFold applies the ContainsFold predicate on the "upstream_multiplier_source" field.
func UpstreamMultiplierSourceContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldUpstreamMultiplierSource, v))
}

// UpstreamMultiplierEffectiveAtEQ applies the EQ predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtNEQ applies the NEQ predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtNEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtIn applies the In predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamMultiplierEffectiveAt, vs...))
}

// UpstreamMultiplierEffectiveAtNotIn applies the NotIn predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtNotIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamMultiplierEffectiveAt, vs...))
}

// UpstreamMultiplierEffectiveAtGT applies the GT predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtGT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtGTE applies the GTE predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtGTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtLT applies the LT predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtLT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtLTE applies the LTE predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtLTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamMultiplierEffectiveAt, v))
}

// UpstreamMultiplierEffectiveAtIsNil applies the IsNil predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamMultiplierEffectiveAt))
}

// UpstreamMultiplierEffectiveAtNotNil applies the NotNil predicate on the "upstream_multiplier_effective_at" field.
func UpstreamMultiplierEffectiveAtNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamMultiplierEffectiveAt))
}

// AccountFinanceProfileIDEQ applies the EQ predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDNEQ applies the NEQ predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDNEQ(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDIn applies the In predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldAccountFinanceProfileID, vs...))
}

// AccountFinanceProfileIDNotIn applies the NotIn predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDNotIn(vs ...int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldAccountFinanceProfileID, vs...))
}

// AccountFinanceProfileIDGT applies the GT predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDGT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDGTE applies the GTE predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDGTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDLT applies the LT predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDLT(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDLTE applies the LTE predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDLTE(v int64) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldAccountFinanceProfileID, v))
}

// AccountFinanceProfileIDIsNil applies the IsNil predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldAccountFinanceProfileID))
}

// AccountFinanceProfileIDNotNil applies the NotNil predicate on the "account_finance_profile_id" field.
func AccountFinanceProfileIDNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldAccountFinanceProfileID))
}

// BillableEQ applies the EQ predicate on the "billable" field.
func BillableEQ(v bool) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldBillable, v))
}

// BillableNEQ applies the NEQ predicate on the "billable" field.
func BillableNEQ(v bool) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldBillable, v))
}

// BillingObservedAtEQ applies the EQ predicate on the "billing_observed_at" field.
func BillingObservedAtEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldBillingObservedAt, v))
}

// BillingObservedAtNEQ applies the NEQ predicate on the "billing_observed_at" field.
func BillingObservedAtNEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldBillingObservedAt, v))
}

// BillingObservedAtIn applies the In predicate on the "billing_observed_at" field.
func BillingObservedAtIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldBillingObservedAt, vs...))
}

// BillingObservedAtNotIn applies the NotIn predicate on the "billing_observed_at" field.
func BillingObservedAtNotIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldBillingObservedAt, vs...))
}

// BillingObservedAtGT applies the GT predicate on the "billing_observed_at" field.
func BillingObservedAtGT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldBillingObservedAt, v))
}

// BillingObservedAtGTE applies the GTE predicate on the "billing_observed_at" field.
func BillingObservedAtGTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldBillingObservedAt, v))
}

// BillingObservedAtLT applies the LT predicate on the "billing_observed_at" field.
func BillingObservedAtLT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldBillingObservedAt, v))
}

// BillingObservedAtLTE applies the LTE predicate on the "billing_observed_at" field.
func BillingObservedAtLTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldBillingObservedAt, v))
}

// BillingObservedAtIsNil applies the IsNil predicate on the "billing_observed_at" field.
func BillingObservedAtIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldBillingObservedAt))
}

// BillingObservedAtNotNil applies the NotNil predicate on the "billing_observed_at" field.
func BillingObservedAtNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldBillingObservedAt))
}

// UpstreamActualChargeEQ applies the EQ predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeNEQ applies the NEQ predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeNEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeIn applies the In predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamActualCharge, vs...))
}

// UpstreamActualChargeNotIn applies the NotIn predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeNotIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamActualCharge, vs...))
}

// UpstreamActualChargeGT applies the GT predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeGT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeGTE applies the GTE predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeGTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeLT applies the LT predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeLT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeLTE applies the LTE predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeLTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamActualCharge, v))
}

// UpstreamActualChargeIsNil applies the IsNil predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamActualCharge))
}

// UpstreamActualChargeNotNil applies the NotNil predicate on the "upstream_actual_charge" field.
func UpstreamActualChargeNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamActualCharge))
}

// UpstreamActualChargeUsdEQ applies the EQ predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdNEQ applies the NEQ predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdNEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdIn applies the In predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamActualChargeUsd, vs...))
}

// UpstreamActualChargeUsdNotIn applies the NotIn predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdNotIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamActualChargeUsd, vs...))
}

// UpstreamActualChargeUsdGT applies the GT predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdGT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdGTE applies the GTE predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdGTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdLT applies the LT predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdLT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdLTE applies the LTE predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdLTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamActualChargeUsd, v))
}

// UpstreamActualChargeUsdIsNil applies the IsNil predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamActualChargeUsd))
}

// UpstreamActualChargeUsdNotNil applies the NotNil predicate on the "upstream_actual_charge_usd" field.
func UpstreamActualChargeUsdNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamActualChargeUsd))
}

// UpstreamStandardChargeEQ applies the EQ predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeNEQ applies the NEQ predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeNEQ(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeIn applies the In predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamStandardCharge, vs...))
}

// UpstreamStandardChargeNotIn applies the NotIn predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeNotIn(vs ...decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamStandardCharge, vs...))
}

// UpstreamStandardChargeGT applies the GT predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeGT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeGTE applies the GTE predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeGTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeLT applies the LT predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeLT(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeLTE applies the LTE predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeLTE(v decimal.Decimal) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamStandardCharge, v))
}

// UpstreamStandardChargeIsNil applies the IsNil predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamStandardCharge))
}

// UpstreamStandardChargeNotNil applies the NotNil predicate on the "upstream_standard_charge" field.
func UpstreamStandardChargeNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamStandardCharge))
}

// UpstreamChargeCurrencyEQ applies the EQ predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyNEQ applies the NEQ predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyIn applies the In predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamChargeCurrency, vs...))
}

// UpstreamChargeCurrencyNotIn applies the NotIn predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamChargeCurrency, vs...))
}

// UpstreamChargeCurrencyGT applies the GT predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyGTE applies the GTE predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyLT applies the LT predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyLTE applies the LTE predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyContains applies the Contains predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyHasPrefix applies the HasPrefix predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyHasSuffix applies the HasSuffix predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyIsNil applies the IsNil predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamChargeCurrency))
}

// UpstreamChargeCurrencyNotNil applies the NotNil predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamChargeCurrency))
}

// UpstreamChargeCurrencyEqualFold applies the EqualFold predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeCurrencyContainsFold applies the ContainsFold predicate on the "upstream_charge_currency" field.
func UpstreamChargeCurrencyContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldUpstreamChargeCurrency, v))
}

// UpstreamChargeUnitSemanticsEQ applies the EQ predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsNEQ applies the NEQ predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsIn applies the In predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamChargeUnitSemantics, vs...))
}

// UpstreamChargeUnitSemanticsNotIn applies the NotIn predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamChargeUnitSemantics, vs...))
}

// UpstreamChargeUnitSemanticsGT applies the GT predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsGTE applies the GTE predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsLT applies the LT predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsLTE applies the LTE predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsContains applies the Contains predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsHasPrefix applies the HasPrefix predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsHasSuffix applies the HasSuffix predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsIsNil applies the IsNil predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamChargeUnitSemantics))
}

// UpstreamChargeUnitSemanticsNotNil applies the NotNil predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamChargeUnitSemantics))
}

// UpstreamChargeUnitSemanticsEqualFold applies the EqualFold predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamChargeUnitSemanticsContainsFold applies the ContainsFold predicate on the "upstream_charge_unit_semantics" field.
func UpstreamChargeUnitSemanticsContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldUpstreamChargeUnitSemantics, v))
}

// UpstreamBillingRequestIDEQ applies the EQ predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDNEQ applies the NEQ predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDNEQ(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDIn applies the In predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldUpstreamBillingRequestID, vs...))
}

// UpstreamBillingRequestIDNotIn applies the NotIn predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDNotIn(vs ...string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldUpstreamBillingRequestID, vs...))
}

// UpstreamBillingRequestIDGT applies the GT predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDGT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDGTE applies the GTE predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDGTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDLT applies the LT predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDLT(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDLTE applies the LTE predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDLTE(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDContains applies the Contains predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDContains(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContains(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDHasPrefix applies the HasPrefix predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDHasPrefix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasPrefix(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDHasSuffix applies the HasSuffix predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDHasSuffix(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldHasSuffix(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDIsNil applies the IsNil predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamBillingRequestID))
}

// UpstreamBillingRequestIDNotNil applies the NotNil predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamBillingRequestID))
}

// UpstreamBillingRequestIDEqualFold applies the EqualFold predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDEqualFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEqualFold(FieldUpstreamBillingRequestID, v))
}

// UpstreamBillingRequestIDContainsFold applies the ContainsFold predicate on the "upstream_billing_request_id" field.
func UpstreamBillingRequestIDContainsFold(v string) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldContainsFold(FieldUpstreamBillingRequestID, v))
}

// UpstreamChargeSnapshotIsNil applies the IsNil predicate on the "upstream_charge_snapshot" field.
func UpstreamChargeSnapshotIsNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIsNull(FieldUpstreamChargeSnapshot))
}

// UpstreamChargeSnapshotNotNil applies the NotNil predicate on the "upstream_charge_snapshot" field.
func UpstreamChargeSnapshotNotNil() predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotNull(FieldUpstreamChargeSnapshot))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageUpstreamAttempt) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageUpstreamAttempt) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageUpstreamAttempt) predicate.UsageUpstreamAttempt {
	return predicate.UsageUpstreamAttempt(sql.NotPredicates(p))
}
