// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/payment"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"net/http"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	proxyRepository := repository.NewProxyRepository(client, db)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig, secretEncryptor)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	userPlatformQuotaRepository := repository.NewUserPlatformQuotaRepository(client)
	serviceUserPlatformQuotaRepository := repository.NewUserPlatformQuotaServiceAdapter(userPlatformQuotaRepository)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig, serviceUserPlatformQuotaRepository)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	affiliateRepository := repository.NewAffiliateRepository(client, db)
	affiliateService := service.NewAffiliateService(affiliateRepository, settingService, apiKeyAuthCacheInvalidator, billingCacheService)
	authService := service.NewAuthService(client, userRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService, affiliateService, serviceUserPlatformQuotaRepository)
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator, affiliateService)
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService, userAttributeService)
	userHandler := handler.NewUserHandler(userService, authService, emailService, emailCache, affiliateService, serviceUserPlatformQuotaRepository)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.ProvideAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository, emailService, settingService, configConfig)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	channelMonitorRepository := repository.NewChannelMonitorRepository(client, db)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	grokQuotaFetcher := service.NewGrokQuotaFetcher()
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	grokOAuthClient := repository.NewGrokOAuthClient()
	grokOAuthService := service.NewGrokOAuthService(proxyRepository, grokOAuthClient)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	grokTokenProvider := service.ProvideGrokTokenProvider(accountRepository, geminiTokenCache, grokOAuthService, oAuthRefreshAPI, tempUnschedCache)
	grokQuotaService := service.ProvideGrokQuotaService(accountRepository, proxyRepository, grokTokenProvider, httpUpstream, configConfig, usageLogRepository)
	usageCache := service.NewUsageCache()
	identityCache := repository.NewIdentityCache(redisClient)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	cnProviderQuotaService := service.ProvideCNProviderQuotaService(accountRepository, httpUpstream, configConfig, tlsFingerprintProfileService)
	cnProviderBalanceService := service.ProvideCNProviderBalanceService(cnProviderQuotaService)
	accountUsageService := service.ProvideAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, grokQuotaFetcher, grokQuotaService, usageCache, identityCache, tlsFingerprintProfileService, cnProviderQuotaService, cnProviderBalanceService)
	channelMonitorService := service.ProvideChannelMonitorService(channelMonitorRepository, secretEncryptor, accountRepository, accountUsageService)
	channelMonitorUserHandler := handler.NewChannelMonitorUserHandler(channelMonitorService, settingService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	groupUsageRollupRepository := repository.NewGroupUsageRollupRepository(db)
	groupUsageRollupStore := repository.ProvideGroupUsageRollupStore(groupUsageRollupRepository)
	customGroupUsageRollup := service.ProvideCustomGroupUsageRollup(groupUsageRollupStore, settingService)
	v := repository.ProvideGroupUsageSummaryProviders(customGroupUsageRollup)
	dashboardService := service.ProvideDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig, v, settingService)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	privacyClientFactory := providePrivacyClientFactory()
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	gatewayCache := repository.NewGatewayCache(redisClient, db)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	openAITeamBlockRepository := repository.NewOpenAITeamBlockRepository(db)
	openAITeamBlockStore := repository.ProvideOpenAITeamBlockStore(openAITeamBlockRepository)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator, openAITeamBlockStore)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.ProvideChannelService(channelRepository, groupRepository, apiKeyAuthCacheInvalidator, pricingService, settingService)
	v2 := repository.ProvideGroupRepositories(groupRepository)
	modelPricingResolver := service.NewModelPricingResolver(channelService, billingService, v2...)
	balanceLowNotifyRepository := repository.NewBalanceLowNotifyRepository(db)
	notificationEmailService := service.NewNotificationEmailService(settingRepository, emailService)
	balanceNotifyService := service.ProvideBalanceNotifyService(emailService, settingRepository, accountRepository, balanceLowNotifyRepository, notificationEmailService)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	semanticCacheAsyncWriter := service.ProvideSemanticCacheAsyncWriter(gatewayCache, settingService)
	openAIGatewayService := service.ProvideOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, grokTokenProvider, modelPricingResolver, channelService, balanceNotifyService, settingService, serviceUserPlatformQuotaRepository, idempotencyRepository, semanticCacheAsyncWriter, cnProviderQuotaService, channelMonitorService)
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, openAIGatewayService)
	adminUserHandler := admin.NewUserHandler(adminService, concurrencyService, serviceUserPlatformQuotaRepository, billingCache)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache)
	accountTestService := service.ProvideAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, grokTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService, settingService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountHandler := admin.ProvideAccountHandler(adminService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, rateLimitService, accountUsageService, accountTestService, geminiTokenProvider, claudeTokenProvider, antigravityGatewayService, httpUpstream, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator, grokQuotaService)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupRepository := repository.NewBackupRepository(db)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, backupRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := admin.NewOpenAIOAuthHandler(openAIOAuthService, adminService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI, openAIGatewayService)
	grokOAuthHandler := admin.NewGrokOAuthHandler(grokOAuthService, adminService, grokQuotaService, tokenRefreshService)
	proxyHandler := admin.NewProxyHandler(adminService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	opsRepository := repository.NewOpsRepository(db)
	identityService := service.NewIdentityService(identityCache)
	digestSessionStore := service.NewDigestSessionStore()
	gatewayService := service.ProvideGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelService, modelPricingResolver, balanceNotifyService, serviceUserPlatformQuotaRepository, semanticCacheAsyncWriter)
	geminiMessagesCompatService := service.ProvideGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig, settingService, semanticCacheAsyncWriter)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	opsService := service.ProvideOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink, secretEncryptor)
	encryptionKey, err := payment.ProvideEncryptionKey(configConfig)
	if err != nil {
		return nil, err
	}
	paymentConfigService := service.ProvidePaymentConfigService(client, settingRepository, encryptionKey)
	registry := payment.ProvideRegistry()
	defaultLoadBalancer := payment.ProvideDefaultLoadBalancer(client, encryptionKey)
	paymentService := service.ProvidePaymentService(client, registry, defaultLoadBalancer, redeemService, subscriptionService, paymentConfigService, userRepository, groupRepository, affiliateService, notificationEmailService)
	settingHandler := handler.ProvideAdminSettingHandler(settingService, emailService, turnstileService, opsService, paymentConfigService, paymentService, userAttributeService, notificationEmailService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	financeDetailRepository := repository.NewFinanceDetailRepository(client, db)
	financeDetailService := service.NewFinanceDetailService(financeDetailRepository)
	financeReportRepository := repository.NewFinanceReportRepository(db)
	financeReportService := service.NewFinanceReportService(financeReportRepository)
	financeAlertRepository := repository.NewFinanceAlertRepository(db)
	financeAlertService := service.NewFinanceAlertService(financeAlertRepository)
	financePaymentFeeRepository := repository.NewFinancePaymentFeeRepository(db)
	financePaymentFeeService := service.NewFinancePaymentFeeService(financePaymentFeeRepository)
	financeBackfillRepository := repository.NewFinanceBackfillRepository(db)
	financeLedgerRepository := repository.NewFinanceLedgerRepository(client, db)
	financePriceLookupRepository := repository.NewFinancePriceLookupRepository(client)
	financePriceSelector := service.NewFinancePriceSelector(financePriceLookupRepository)
	financeCostCalculator := service.NewFinanceCostCalculator()
	financeUsageScanner := service.NewFinanceUsageScanner(financeLedgerRepository, financePriceSelector, financeCostCalculator)
	financeBackfillService := service.NewFinanceBackfillService(financeBackfillRepository, financeLedgerRepository, financeUsageScanner, configConfig)
	financeReconciliationRepository := repository.NewFinanceReconciliationRepository(db)
	financeReconciliationService := service.NewFinanceReconciliationService(financeReconciliationRepository)
	financeExportRepository := repository.NewFinanceExportRepository(db)
	financeExportService := service.NewFinanceExportService(financeExportRepository, financeReportService, configConfig)
	promotionCreditReconciliationRepository := repository.NewPromotionCreditReconciliationRepository(db)
	promotionCreditReconciliationService := service.NewPromotionCreditReconciliationService(promotionCreditReconciliationRepository)
	financeSettlementRepository := repository.NewFinanceSettlementRepository(db)
	accountFinanceSettlementService := service.NewAccountFinanceSettlementService(financeSettlementRepository)
	accountFinanceProfileRepository := repository.NewAccountFinanceProfileRepository(db, accountRepository, schedulerCache)
	accountFinanceProfileService := service.NewAccountFinanceProfileService(accountFinanceProfileRepository)
	financeInitializationAccountService := service.BindFinanceInitializationAccountService(adminService)
	upstreamRepository := repository.NewUpstreamRepository(db)
	upstreamService := service.NewUpstreamService(upstreamRepository, settingRepository, emailService)
	financeInitializationUpstreamService := service.BindFinanceInitializationUpstreamService(upstreamService)
	upstreamWalletRepository := repository.NewUpstreamWalletRepository(db)
	upstreamWalletService := service.NewUpstreamWalletService(upstreamWalletRepository, secretEncryptor)
	financeInitializationWalletService := service.BindFinanceInitializationWalletService(upstreamWalletService)
	upstreamFundRepository := repository.NewUpstreamFundRepository(db)
	upstreamFundBalanceRecorder := repository.NewUpstreamFundBalanceRepository(db)
	upstreamFundService := service.ProvideUpstreamFundService(upstreamWalletService, upstreamFundRepository, upstreamFundBalanceRecorder)
	financeInitializationFundService := service.BindFinanceInitializationFundService(upstreamFundService)
	financeInitializationProfileService := service.BindFinanceInitializationProfileService(accountFinanceProfileService)
	financeInitializationService := service.NewFinanceInitializationService(financeInitializationAccountService, financeInitializationUpstreamService, financeInitializationWalletService, financeInitializationFundService, financeInitializationProfileService)
	financeFXRateRepository := repository.NewFinanceFXRateRepository(db)
	financeFXRateService := service.NewFinanceFXRateService(financeFXRateRepository)
	financeHandler := handler.ProvideFinanceHandler(financeDetailService, financeReportService, financeAlertService, financePaymentFeeService, financeBackfillService, financeReconciliationService, financeExportService, promotionCreditReconciliationService, accountFinanceSettlementService, accountFinanceProfileService, financeInitializationService, financeFXRateService)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	channelHandler := admin.NewChannelHandler(channelService, billingService, pricingService)
	channelMonitorHandler := admin.NewChannelMonitorHandler(channelMonitorService)
	channelMonitorRequestTemplateRepository := repository.NewChannelMonitorRequestTemplateRepository(client, db)
	channelMonitorRequestTemplateService := service.NewChannelMonitorRequestTemplateService(channelMonitorRequestTemplateRepository)
	channelMonitorRequestTemplateHandler := admin.NewChannelMonitorRequestTemplateHandler(channelMonitorRequestTemplateService)
	contentModerationRepository := repository.NewContentModerationRepository(db)
	contentModerationHashCache := repository.NewContentModerationHashCache(redisClient)
	contentModerationService := service.NewContentModerationService(settingRepository, contentModerationRepository, contentModerationHashCache, groupRepository, userRepository, apiKeyAuthCacheInvalidator, emailService)
	contentModerationHandler := admin.NewContentModerationHandler(contentModerationService)
	paymentHandler := admin.NewPaymentHandler(paymentService, paymentConfigService)
	affiliateHandler := admin.NewAffiliateHandler(affiliateService, adminService)
	upstreamHandler := admin.NewUpstreamHandler(upstreamService)
	upstreamFinanceAdapterRegistry := service.NewUpstreamFinanceAdapterRegistry()
	upstreamFinanceSyncRepository := repository.NewUpstreamFinanceSyncRepository(db)
	upstreamFinanceProtocolRepository := repository.NewUpstreamFinanceProtocolRepository(db)
	upstreamFinanceHTTPExecutor := service.NewUpstreamFinanceHTTPExecutor()
	accountFinanceSnapshotRepository := repository.NewAccountFinanceSnapshotRepository(db)
	accountFinanceMultiplierAccountRepository, err := repository.BindAccountFinanceMultiplierAccountRepository(accountRepository)
	if err != nil {
		return nil, err
	}
	accountFinanceSnapshotService := service.NewAccountFinanceSnapshotService(accountFinanceSnapshotRepository, accountFinanceMultiplierAccountRepository, accountFinanceSettlementService)
	upstreamFinanceSyncAccountRepository := repository.BindUpstreamFinanceSyncAccountRepository(accountRepository)
	upstreamFinanceSyncService := service.NewUpstreamFinanceSyncService(upstreamWalletService, upstreamFinanceAdapterRegistry, upstreamFinanceSyncRepository, upstreamFinanceProtocolRepository, upstreamFinanceHTTPExecutor, upstreamFundService, accountFinanceSnapshotService, upstreamFinanceSyncAccountRepository)
	upstreamWalletHandler := admin.NewUpstreamWalletHandler(upstreamWalletService, upstreamFinanceSyncService, upstreamFundService)
	upstreamFinanceProtocolService := service.NewUpstreamFinanceProtocolService(upstreamFinanceProtocolRepository, upstreamFinanceHTTPExecutor)
	accountService := service.NewAccountService(accountRepository, groupRepository)
	upstreamFinanceProtocolHandler := admin.NewUpstreamFinanceProtocolHandler(upstreamFinanceProtocolService, accountService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, groupHandler, accountHandler, adminAnnouncementHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, grokOAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, financeHandler, userAttributeHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, channelHandler, channelMonitorHandler, channelMonitorRequestTemplateHandler, contentModerationHandler, paymentHandler, affiliateHandler, upstreamHandler, upstreamWalletHandler, upstreamFinanceProtocolHandler)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig)
	gatewayHandler := handler.NewGatewayHandler(gatewayService, geminiMessagesCompatService, antigravityGatewayService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, userMessageQueueService, configConfig, settingService)
	openAIGatewayHandler := handler.ProvideOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, contentModerationService, grokQuotaService, configConfig)
	seedaceVideoService := service.ProvideSeedaceVideoService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, channelService, billingService, modelPricingResolver, apiKeyService, billingCacheService, deferredService, balanceNotifyService, serviceUserPlatformQuotaRepository, httpUpstream, configConfig, settingService)
	seedaceVideoHandler := handler.NewSeedaceVideoHandler(seedaceVideoService)
	seedaceVideoHistoryService := service.NewSeedaceVideoHistoryService(client)
	userVideoGenerationHandler := handler.NewUserVideoGenerationHandler(apiKeyService, seedaceVideoService, seedaceVideoHistoryService)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo, notificationEmailService)
	totpHandler := handler.NewTotpHandler(totpService)
	handlerPaymentHandler := handler.NewPaymentHandler(paymentService, paymentConfigService, channelService)
	paymentWebhookHandler := handler.NewPaymentWebhookHandler(paymentService, registry)
	availableChannelHandler := handler.NewAvailableChannelHandler(channelService, apiKeyService, settingService)
	modelSquareService := service.NewModelSquareService(groupRepository, accountRepository, userRepository, userGroupRateRepository, channelService, pricingService, modelPricingResolver, settingService, configConfig)
	modelSquareHandler := handler.NewModelSquareHandler(modelSquareService, settingService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	handlers := handler.ProvideHandlers(authHandler, userHandler, apiKeyHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, channelMonitorUserHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, seedaceVideoHandler, userVideoGenerationHandler, handlerSettingHandler, totpHandler, handlerPaymentHandler, paymentWebhookHandler, availableChannelHandler, modelSquareHandler, idempotencyCoordinator, idempotencyCleanupService)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, db, redisClient, configConfig, channelMonitorService, settingRepository, opsService)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	balanceLowNotifyScanner := service.ProvideBalanceLowNotifyScanner(balanceNotifyService)
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository)
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository, settingRepository, notificationEmailService)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, configConfig)
	paymentOrderExpiryService := service.ProvidePaymentOrderExpiryService(paymentService)
	channelMonitorRunner := service.ProvideChannelMonitorRunner(channelMonitorService, settingService)
	financeCatalogVersionRepository := repository.NewFinanceCatalogVersionRepository(client)
	financeCatalogVersionSync := service.NewFinanceCatalogVersionSync(pricingService, financeCatalogVersionRepository)
	financeRevenueRecognitionRepository := repository.NewFinanceRevenueRecognitionRepository(db)
	financeRevenueRecognitionService := service.NewFinanceRevenueRecognitionService(financeRevenueRecognitionRepository, configConfig)
	financeRuntime := service.ProvideFinanceRuntime(financeCatalogVersionSync, financeUsageScanner, financeAlertService, financeRevenueRecognitionService, financeBackfillService, financeExportService)
	upstreamFinanceSyncRuntime := service.ProvideUpstreamFinanceSyncRuntime(upstreamFinanceSyncService, upstreamFinanceSyncRepository)
	v3 := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, schedulerSnapshotService, tokenRefreshService, balanceLowNotifyScanner, accountExpiryService, subscriptionExpiryService, usageCleanupService, idempotencyCleanupService, pricingService, emailQueueService, billingCacheService, usageRecordWorkerPool, subscriptionService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, grokOAuthService, openAIGatewayService, scheduledTestRunnerService, backupService, paymentOrderExpiryService, channelMonitorRunner, customGroupUsageRollup, financeRuntime, upstreamFinanceSyncRuntime)
	application := &Application{
		Server:  httpServer,
		Cleanup: v3,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	opsMetricsCollector *service.OpsMetricsCollector,
	opsAggregation *service.OpsAggregationService,
	opsAlertEvaluator *service.OpsAlertEvaluatorService,
	opsCleanup *service.OpsCleanupService,
	opsScheduledReport *service.OpsScheduledReportService,
	opsSystemLogSink *service.OpsSystemLogSink,
	schedulerSnapshot *service.SchedulerSnapshotService,
	tokenRefresh *service.TokenRefreshService,
	balanceLowNotifyScanner *service.BalanceLowNotifyScanner,
	accountExpiry *service.AccountExpiryService,
	subscriptionExpiry *service.SubscriptionExpiryService,
	usageCleanup *service.UsageCleanupService,
	idempotencyCleanup *service.IdempotencyCleanupService,
	pricing *service.PricingService,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	usageRecordWorkerPool *service.UsageRecordWorkerPool,
	subscriptionService *service.SubscriptionService,
	oauth *service.OAuthService,
	openaiOAuth *service.OpenAIOAuthService,
	geminiOAuth *service.GeminiOAuthService,
	antigravityOAuth *service.AntigravityOAuthService,
	grokOAuth *service.GrokOAuthService,
	openAIGateway *service.OpenAIGatewayService,
	scheduledTestRunner *service.ScheduledTestRunnerService,
	backupSvc *service.BackupService,
	paymentOrderExpiry *service.PaymentOrderExpiryService,
	channelMonitorRunner *service.ChannelMonitorRunner,
	groupUsageRollup *service.CustomGroupUsageRollup,
	financeRuntime *service.FinanceRuntime,
	upstreamFinanceSyncRuntime *service.UpstreamFinanceSyncRuntime,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		type cleanupStep struct {
			name string
			fn   func() error
		}

		parallelSteps := []cleanupStep{
			{"CustomGroupUsageRollup", func() error {
				if groupUsageRollup != nil {
					groupUsageRollup.Stop()
				}
				return nil
			}},
			{"UpstreamFinanceSyncRuntime", func() error {
				if upstreamFinanceSyncRuntime != nil {
					upstreamFinanceSyncRuntime.Stop()
				}
				return nil
			}},
			{"FinanceRuntime", func() error {
				if financeRuntime != nil {
					financeRuntime.Stop()
				}
				return nil
			}},
			{"OpsScheduledReportService", func() error {
				if opsScheduledReport != nil {
					opsScheduledReport.Stop()
				}
				return nil
			}},
			{"OpsCleanupService", func() error {
				if opsCleanup != nil {
					opsCleanup.Stop()
				}
				return nil
			}},
			{"OpsSystemLogSink", func() error {
				if opsSystemLogSink != nil {
					opsSystemLogSink.Stop()
				}
				return nil
			}},
			{"OpsAlertEvaluatorService", func() error {
				if opsAlertEvaluator != nil {
					opsAlertEvaluator.Stop()
				}
				return nil
			}},
			{"OpsAggregationService", func() error {
				if opsAggregation != nil {
					opsAggregation.Stop()
				}
				return nil
			}},
			{"OpsMetricsCollector", func() error {
				if opsMetricsCollector != nil {
					opsMetricsCollector.Stop()
				}
				return nil
			}},
			{"SchedulerSnapshotService", func() error {
				if schedulerSnapshot != nil {
					schedulerSnapshot.Stop()
				}
				return nil
			}},
			{"UsageCleanupService", func() error {
				if usageCleanup != nil {
					usageCleanup.Stop()
				}
				return nil
			}},
			{"IdempotencyCleanupService", func() error {
				if idempotencyCleanup != nil {
					idempotencyCleanup.Stop()
				}
				return nil
			}},
			{"TokenRefreshService", func() error {
				tokenRefresh.Stop()
				return nil
			}},
			{"BalanceLowNotifyScanner", func() error {
				if balanceLowNotifyScanner != nil {
					balanceLowNotifyScanner.Stop()
				}
				return nil
			}},
			{"AccountExpiryService", func() error {
				accountExpiry.Stop()
				return nil
			}},
			{"SubscriptionExpiryService", func() error {
				subscriptionExpiry.Stop()
				return nil
			}},
			{"SubscriptionService", func() error {
				if subscriptionService != nil {
					subscriptionService.Stop()
				}
				return nil
			}},
			{"PricingService", func() error {
				pricing.Stop()
				return nil
			}},
			{"EmailQueueService", func() error {
				emailQueue.Stop()
				return nil
			}},
			{"BillingCacheService", func() error {
				billingCache.Stop()
				return nil
			}},
			{"UsageRecordWorkerPool", func() error {
				if usageRecordWorkerPool != nil {
					usageRecordWorkerPool.Stop()
				}
				return nil
			}},
			{"OAuthService", func() error {
				oauth.Stop()
				return nil
			}},
			{"OpenAIOAuthService", func() error {
				openaiOAuth.Stop()
				return nil
			}},
			{"GeminiOAuthService", func() error {
				geminiOAuth.Stop()
				return nil
			}},
			{"AntigravityOAuthService", func() error {
				antigravityOAuth.Stop()
				return nil
			}},
			{"GrokOAuthService", func() error {
				grokOAuth.Stop()
				return nil
			}},
			{"OpenAIWSPool", func() error {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
				return nil
			}},
			{"ScheduledTestRunnerService", func() error {
				if scheduledTestRunner != nil {
					scheduledTestRunner.Stop()
				}
				return nil
			}},
			{"BackupService", func() error {
				if backupSvc != nil {
					backupSvc.Stop()
				}
				return nil
			}},
			{"PaymentOrderExpiryService", func() error {
				if paymentOrderExpiry != nil {
					paymentOrderExpiry.Stop()
				}
				return nil
			}},
			{"ChannelMonitorRunner", func() error {
				if channelMonitorRunner != nil {
					channelMonitorRunner.Stop()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		runParallel := func(steps []cleanupStep) {
			var wg sync.WaitGroup
			for i := range steps {
				step := steps[i]
				wg.Add(1)
				go func() {
					defer wg.Done()
					if err := step.fn(); err != nil {
						log.Printf("[Cleanup] %s failed: %v", step.name, err)
						return
					}
					log.Printf("[Cleanup] %s succeeded", step.name)
				}()
			}
			wg.Wait()
		}

		runSequential := func(steps []cleanupStep) {
			for i := range steps {
				step := steps[i]
				if err := step.fn(); err != nil {
					log.Printf("[Cleanup] %s failed: %v", step.name, err)
					continue
				}
				log.Printf("[Cleanup] %s succeeded", step.name)
			}
		}

		runParallel(parallelSteps)
		runSequential(infraSteps)

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
}
