// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usageupstreamattempt"
	"github.com/shopspring/decimal"
)

// UsageUpstreamAttempt is the model entity for the UsageUpstreamAttempt schema.
type UsageUpstreamAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// AttemptNo holds the value of the "attempt_no" field.
	AttemptNo int `json:"attempt_no,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID *int64 `json:"channel_id,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// ServiceTier holds the value of the "service_tier" field.
	ServiceTier *string `json:"service_tier,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int64 `json:"cache_read_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int64 `json:"cache_creation_tokens,omitempty"`
	// CacheCreation5mTokens holds the value of the "cache_creation_5m_tokens" field.
	CacheCreation5mTokens int64 `json:"cache_creation_5m_tokens,omitempty"`
	// CacheCreation1hTokens holds the value of the "cache_creation_1h_tokens" field.
	CacheCreation1hTokens int64 `json:"cache_creation_1h_tokens,omitempty"`
	// RequestCount holds the value of the "request_count" field.
	RequestCount int64 `json:"request_count,omitempty"`
	// ImageCount holds the value of the "image_count" field.
	ImageCount int64 `json:"image_count,omitempty"`
	// VideoSeconds holds the value of the "video_seconds" field.
	VideoSeconds int64 `json:"video_seconds,omitempty"`
	// UpstreamCostMultiplier holds the value of the "upstream_cost_multiplier" field.
	UpstreamCostMultiplier *decimal.Decimal `json:"upstream_cost_multiplier,omitempty"`
	// UpstreamMultiplierChangeID holds the value of the "upstream_multiplier_change_id" field.
	UpstreamMultiplierChangeID *int64 `json:"upstream_multiplier_change_id,omitempty"`
	// UpstreamMultiplierSource holds the value of the "upstream_multiplier_source" field.
	UpstreamMultiplierSource *string `json:"upstream_multiplier_source,omitempty"`
	// UpstreamMultiplierEffectiveAt holds the value of the "upstream_multiplier_effective_at" field.
	UpstreamMultiplierEffectiveAt *time.Time `json:"upstream_multiplier_effective_at,omitempty"`
	// AccountFinanceProfileID holds the value of the "account_finance_profile_id" field.
	AccountFinanceProfileID *int64 `json:"account_finance_profile_id,omitempty"`
	// Billable holds the value of the "billable" field.
	Billable bool `json:"billable,omitempty"`
	// BillingObservedAt holds the value of the "billing_observed_at" field.
	BillingObservedAt *time.Time `json:"billing_observed_at,omitempty"`
	// UpstreamActualCharge holds the value of the "upstream_actual_charge" field.
	UpstreamActualCharge *decimal.Decimal `json:"upstream_actual_charge,omitempty"`
	// UpstreamActualChargeUsd holds the value of the "upstream_actual_charge_usd" field.
	UpstreamActualChargeUsd *decimal.Decimal `json:"upstream_actual_charge_usd,omitempty"`
	// UpstreamStandardCharge holds the value of the "upstream_standard_charge" field.
	UpstreamStandardCharge *decimal.Decimal `json:"upstream_standard_charge,omitempty"`
	// UpstreamChargeCurrency holds the value of the "upstream_charge_currency" field.
	UpstreamChargeCurrency *string `json:"upstream_charge_currency,omitempty"`
	// UpstreamChargeUnitSemantics holds the value of the "upstream_charge_unit_semantics" field.
	UpstreamChargeUnitSemantics *string `json:"upstream_charge_unit_semantics,omitempty"`
	// UpstreamBillingRequestID holds the value of the "upstream_billing_request_id" field.
	UpstreamBillingRequestID *string `json:"upstream_billing_request_id,omitempty"`
	// UpstreamChargeSnapshot holds the value of the "upstream_charge_snapshot" field.
	UpstreamChargeSnapshot map[string]interface{} `json:"upstream_charge_snapshot,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageUpstreamAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usageupstreamattempt.FieldUpstreamCostMultiplier, usageupstreamattempt.FieldUpstreamActualCharge, usageupstreamattempt.FieldUpstreamActualChargeUsd, usageupstreamattempt.FieldUpstreamStandardCharge:
			values[i] = &sql.NullScanner{S: new(decimal.Decimal)}
		case usageupstreamattempt.FieldUpstreamChargeSnapshot:
			values[i] = new([]byte)
		case usageupstreamattempt.FieldBillable:
			values[i] = new(sql.NullBool)
		case usageupstreamattempt.FieldID, usageupstreamattempt.FieldUsageLogID, usageupstreamattempt.FieldAttemptNo, usageupstreamattempt.FieldAccountID, usageupstreamattempt.FieldChannelID, usageupstreamattempt.FieldInputTokens, usageupstreamattempt.FieldOutputTokens, usageupstreamattempt.FieldCacheReadTokens, usageupstreamattempt.FieldCacheCreationTokens, usageupstreamattempt.FieldCacheCreation5mTokens, usageupstreamattempt.FieldCacheCreation1hTokens, usageupstreamattempt.FieldRequestCount, usageupstreamattempt.FieldImageCount, usageupstreamattempt.FieldVideoSeconds, usageupstreamattempt.FieldUpstreamMultiplierChangeID, usageupstreamattempt.FieldAccountFinanceProfileID:
			values[i] = new(sql.NullInt64)
		case usageupstreamattempt.FieldRequestID, usageupstreamattempt.FieldUpstreamModel, usageupstreamattempt.FieldServiceTier, usageupstreamattempt.FieldUpstreamMultiplierSource, usageupstreamattempt.FieldUpstreamChargeCurrency, usageupstreamattempt.FieldUpstreamChargeUnitSemantics, usageupstreamattempt.FieldUpstreamBillingRequestID:
			values[i] = new(sql.NullString)
		case usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt, usageupstreamattempt.FieldBillingObservedAt, usageupstreamattempt.FieldCompletedAt, usageupstreamattempt.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageUpstreamAttempt fields.
func (_m *UsageUpstreamAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usageupstreamattempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usageupstreamattempt.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usageupstreamattempt.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usageupstreamattempt.FieldAttemptNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_no", values[i])
			} else if value.Valid {
				_m.AttemptNo = int(value.Int64)
			}
		case usageupstreamattempt.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usageupstreamattempt.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case usageupstreamattempt.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case usageupstreamattempt.FieldServiceTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_tier", values[i])
			} else if value.Valid {
				_m.ServiceTier = new(string)
				*_m.ServiceTier = value.String
			}
		case usageupstreamattempt.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case usageupstreamattempt.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case usageupstreamattempt.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = value.Int64
			}
		case usageupstreamattempt.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = value.Int64
			}
		case usageupstreamattempt.FieldCacheCreation5mTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_5m_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation5mTokens = value.Int64
			}
		case usageupstreamattempt.FieldCacheCreation1hTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_1h_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation1hTokens = value.Int64
			}
		case usageupstreamattempt.FieldRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_count", values[i])
			} else if value.Valid {
				_m.RequestCount = value.Int64
			}
		case usageupstreamattempt.FieldImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_count", values[i])
			} else if value.Valid {
				_m.ImageCount = value.Int64
			}
		case usageupstreamattempt.FieldVideoSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_seconds", values[i])
			} else if value.Valid {
				_m.VideoSeconds = value.Int64
			}
		case usageupstreamattempt.FieldUpstreamCostMultiplier:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_cost_multiplier", values[i])
			} else if value.Valid {
				_m.UpstreamCostMultiplier = new(decimal.Decimal)
				*_m.UpstreamCostMultiplier = *value.S.(*decimal.Decimal)
			}
		case usageupstreamattempt.FieldUpstreamMultiplierChangeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_multiplier_change_id", values[i])
			} else if value.Valid {
				_m.UpstreamMultiplierChangeID = new(int64)
				*_m.UpstreamMultiplierChangeID = value.Int64
			}
		case usageupstreamattempt.FieldUpstreamMultiplierSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_multiplier_source", values[i])
			} else if value.Valid {
				_m.UpstreamMultiplierSource = new(string)
				*_m.UpstreamMultiplierSource = value.String
			}
		case usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_multiplier_effective_at", values[i])
			} else if value.Valid {
				_m.UpstreamMultiplierEffectiveAt = new(time.Time)
				*_m.UpstreamMultiplierEffectiveAt = value.Time
			}
		case usageupstreamattempt.FieldAccountFinanceProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_finance_profile_id", values[i])
			} else if value.Valid {
				_m.AccountFinanceProfileID = new(int64)
				*_m.AccountFinanceProfileID = value.Int64
			}
		case usageupstreamattempt.FieldBillable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field billable", values[i])
			} else if value.Valid {
				_m.Billable = value.Bool
			}
		case usageupstreamattempt.FieldBillingObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field billing_observed_at", values[i])
			} else if value.Valid {
				_m.BillingObservedAt = new(time.Time)
				*_m.BillingObservedAt = value.Time
			}
		case usageupstreamattempt.FieldUpstreamActualCharge:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_actual_charge", values[i])
			} else if value.Valid {
				_m.UpstreamActualCharge = new(decimal.Decimal)
				*_m.UpstreamActualCharge = *value.S.(*decimal.Decimal)
			}
		case usageupstreamattempt.FieldUpstreamActualChargeUsd:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_actual_charge_usd", values[i])
			} else if value.Valid {
				_m.UpstreamActualChargeUsd = new(decimal.Decimal)
				*_m.UpstreamActualChargeUsd = *value.S.(*decimal.Decimal)
			}
		case usageupstreamattempt.FieldUpstreamStandardCharge:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_standard_charge", values[i])
			} else if value.Valid {
				_m.UpstreamStandardCharge = new(decimal.Decimal)
				*_m.UpstreamStandardCharge = *value.S.(*decimal.Decimal)
			}
		case usageupstreamattempt.FieldUpstreamChargeCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_charge_currency", values[i])
			} else if value.Valid {
				_m.UpstreamChargeCurrency = new(string)
				*_m.UpstreamChargeCurrency = value.String
			}
		case usageupstreamattempt.FieldUpstreamChargeUnitSemantics:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_charge_unit_semantics", values[i])
			} else if value.Valid {
				_m.UpstreamChargeUnitSemantics = new(string)
				*_m.UpstreamChargeUnitSemantics = value.String
			}
		case usageupstreamattempt.FieldUpstreamBillingRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_billing_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamBillingRequestID = new(string)
				*_m.UpstreamBillingRequestID = value.String
			}
		case usageupstreamattempt.FieldUpstreamChargeSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_charge_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamChargeSnapshot); err != nil {
					return fmt.Errorf("unmarshal field upstream_charge_snapshot: %w", err)
				}
			}
		case usageupstreamattempt.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case usageupstreamattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageUpstreamAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *UsageUpstreamAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UsageUpstreamAttempt.
// Note that you need to call UsageUpstreamAttempt.Unwrap() before calling this method if this UsageUpstreamAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageUpstreamAttempt) Update() *UsageUpstreamAttemptUpdateOne {
	return NewUsageUpstreamAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageUpstreamAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageUpstreamAttempt) Unwrap() *UsageUpstreamAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageUpstreamAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageUpstreamAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("UsageUpstreamAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("attempt_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNo))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	if v := _m.ServiceTier; v != nil {
		builder.WriteString("service_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_5m_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation5mTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_1h_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation1hTokens))
	builder.WriteString(", ")
	builder.WriteString("request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestCount))
	builder.WriteString(", ")
	builder.WriteString("image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageCount))
	builder.WriteString(", ")
	builder.WriteString("video_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoSeconds))
	builder.WriteString(", ")
	if v := _m.UpstreamCostMultiplier; v != nil {
		builder.WriteString("upstream_cost_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamMultiplierChangeID; v != nil {
		builder.WriteString("upstream_multiplier_change_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamMultiplierSource; v != nil {
		builder.WriteString("upstream_multiplier_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamMultiplierEffectiveAt; v != nil {
		builder.WriteString("upstream_multiplier_effective_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AccountFinanceProfileID; v != nil {
		builder.WriteString("account_finance_profile_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Billable))
	builder.WriteString(", ")
	if v := _m.BillingObservedAt; v != nil {
		builder.WriteString("billing_observed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamActualCharge; v != nil {
		builder.WriteString("upstream_actual_charge=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamActualChargeUsd; v != nil {
		builder.WriteString("upstream_actual_charge_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamStandardCharge; v != nil {
		builder.WriteString("upstream_standard_charge=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamChargeCurrency; v != nil {
		builder.WriteString("upstream_charge_currency=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamChargeUnitSemantics; v != nil {
		builder.WriteString("upstream_charge_unit_semantics=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamBillingRequestID; v != nil {
		builder.WriteString("upstream_billing_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_charge_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamChargeSnapshot))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageUpstreamAttempts is a parsable slice of UsageUpstreamAttempt.
type UsageUpstreamAttempts []*UsageUpstreamAttempt
