// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usageupstreamattempt"
	"github.com/shopspring/decimal"
)

// UsageUpstreamAttemptUpdate is the builder for updating UsageUpstreamAttempt entities.
type UsageUpstreamAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *UsageUpstreamAttemptMutation
}

// Where appends a list predicates to the UsageUpstreamAttemptUpdate builder.
func (_u *UsageUpstreamAttemptUpdate) Where(ps ...predicate.UsageUpstreamAttempt) *UsageUpstreamAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetUsageLogID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUsageLogID(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageUpstreamAttemptUpdate) AddUsageLogID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetRequestID(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableRequestID(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAttemptNo sets the "attempt_no" field.
func (_u *UsageUpstreamAttemptUpdate) SetAttemptNo(v int) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetAttemptNo()
	_u.mutation.SetAttemptNo(v)
	return _u
}

// SetNillableAttemptNo sets the "attempt_no" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableAttemptNo(v *int) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetAttemptNo(*v)
	}
	return _u
}

// AddAttemptNo adds value to the "attempt_no" field.
func (_u *UsageUpstreamAttemptUpdate) AddAttemptNo(v int) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddAttemptNo(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetAccountID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableAccountID(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageUpstreamAttemptUpdate) AddAccountID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetChannelID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableChannelID(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdate) AddChannelID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdate) ClearChannelID() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamModel(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamModel(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *UsageUpstreamAttemptUpdate) SetServiceTier(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableServiceTier(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *UsageUpstreamAttemptUpdate) ClearServiceTier() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetInputTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableInputTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddInputTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetOutputTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableOutputTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddOutputTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetCacheReadTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableCacheReadTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddCacheReadTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetCacheCreationTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableCacheCreationTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddCacheCreationTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetCacheCreation5mTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetCacheCreation5mTokens()
	_u.mutation.SetCacheCreation5mTokens(v)
	return _u
}

// SetNillableCacheCreation5mTokens sets the "cache_creation_5m_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableCacheCreation5mTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetCacheCreation5mTokens(*v)
	}
	return _u
}

// AddCacheCreation5mTokens adds value to the "cache_creation_5m_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddCacheCreation5mTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddCacheCreation5mTokens(v)
	return _u
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) SetCacheCreation1hTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetCacheCreation1hTokens()
	_u.mutation.SetCacheCreation1hTokens(v)
	return _u
}

// SetNillableCacheCreation1hTokens sets the "cache_creation_1h_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableCacheCreation1hTokens(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetCacheCreation1hTokens(*v)
	}
	return _u
}

// AddCacheCreation1hTokens adds value to the "cache_creation_1h_tokens" field.
func (_u *UsageUpstreamAttemptUpdate) AddCacheCreation1hTokens(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddCacheCreation1hTokens(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageUpstreamAttemptUpdate) SetRequestCount(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableRequestCount(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageUpstreamAttemptUpdate) AddRequestCount(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *UsageUpstreamAttemptUpdate) SetImageCount(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableImageCount(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *UsageUpstreamAttemptUpdate) AddImageCount(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetVideoSeconds sets the "video_seconds" field.
func (_u *UsageUpstreamAttemptUpdate) SetVideoSeconds(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetVideoSeconds()
	_u.mutation.SetVideoSeconds(v)
	return _u
}

// SetNillableVideoSeconds sets the "video_seconds" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableVideoSeconds(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetVideoSeconds(*v)
	}
	return _u
}

// AddVideoSeconds adds value to the "video_seconds" field.
func (_u *UsageUpstreamAttemptUpdate) AddVideoSeconds(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddVideoSeconds(v)
	return _u
}

// SetUpstreamCostMultiplier sets the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamCostMultiplier(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUpstreamCostMultiplier()
	_u.mutation.SetUpstreamCostMultiplier(v)
	return _u
}

// SetNillableUpstreamCostMultiplier sets the "upstream_cost_multiplier" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamCostMultiplier(v *decimal.Decimal) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamCostMultiplier(*v)
	}
	return _u
}

// AddUpstreamCostMultiplier adds value to the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdate) AddUpstreamCostMultiplier(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUpstreamCostMultiplier(v)
	return _u
}

// ClearUpstreamCostMultiplier clears the value of the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamCostMultiplier() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamCostMultiplier()
	return _u
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamMultiplierChangeID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUpstreamMultiplierChangeID()
	_u.mutation.SetUpstreamMultiplierChangeID(v)
	return _u
}

// SetNillableUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamMultiplierChangeID(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierChangeID(*v)
	}
	return _u
}

// AddUpstreamMultiplierChangeID adds value to the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdate) AddUpstreamMultiplierChangeID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUpstreamMultiplierChangeID(v)
	return _u
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamMultiplierChangeID() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamMultiplierChangeID()
	return _u
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamMultiplierSource(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamMultiplierSource(v)
	return _u
}

// SetNillableUpstreamMultiplierSource sets the "upstream_multiplier_source" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamMultiplierSource(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierSource(*v)
	}
	return _u
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamMultiplierSource() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamMultiplierSource()
	return _u
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamMultiplierEffectiveAt(v)
	return _u
}

// SetNillableUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamMultiplierEffectiveAt(v *time.Time) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamMultiplierEffectiveAt(*v)
	}
	return _u
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamMultiplierEffectiveAt() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamMultiplierEffectiveAt()
	return _u
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetAccountFinanceProfileID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetAccountFinanceProfileID()
	_u.mutation.SetAccountFinanceProfileID(v)
	return _u
}

// SetNillableAccountFinanceProfileID sets the "account_finance_profile_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableAccountFinanceProfileID(v *int64) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetAccountFinanceProfileID(*v)
	}
	return _u
}

// AddAccountFinanceProfileID adds value to the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdate) AddAccountFinanceProfileID(v int64) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddAccountFinanceProfileID(v)
	return _u
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdate) ClearAccountFinanceProfileID() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearAccountFinanceProfileID()
	return _u
}

// SetBillable sets the "billable" field.
func (_u *UsageUpstreamAttemptUpdate) SetBillable(v bool) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetBillable(v)
	return _u
}

// SetNillableBillable sets the "billable" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableBillable(v *bool) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetBillable(*v)
	}
	return _u
}

// SetBillingObservedAt sets the "billing_observed_at" field.
func (_u *UsageUpstreamAttemptUpdate) SetBillingObservedAt(v time.Time) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetBillingObservedAt(v)
	return _u
}

// SetNillableBillingObservedAt sets the "billing_observed_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableBillingObservedAt(v *time.Time) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetBillingObservedAt(*v)
	}
	return _u
}

// ClearBillingObservedAt clears the value of the "billing_observed_at" field.
func (_u *UsageUpstreamAttemptUpdate) ClearBillingObservedAt() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearBillingObservedAt()
	return _u
}

// SetUpstreamActualCharge sets the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamActualCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUpstreamActualCharge()
	_u.mutation.SetUpstreamActualCharge(v)
	return _u
}

// SetNillableUpstreamActualCharge sets the "upstream_actual_charge" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamActualCharge(v *decimal.Decimal) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamActualCharge(*v)
	}
	return _u
}

// AddUpstreamActualCharge adds value to the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdate) AddUpstreamActualCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUpstreamActualCharge(v)
	return _u
}

// ClearUpstreamActualCharge clears the value of the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamActualCharge() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamActualCharge()
	return _u
}

// SetUpstreamActualChargeUsd sets the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamActualChargeUsd(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUpstreamActualChargeUsd()
	_u.mutation.SetUpstreamActualChargeUsd(v)
	return _u
}

// SetNillableUpstreamActualChargeUsd sets the "upstream_actual_charge_usd" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamActualChargeUsd(v *decimal.Decimal) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamActualChargeUsd(*v)
	}
	return _u
}

// AddUpstreamActualChargeUsd adds value to the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdate) AddUpstreamActualChargeUsd(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUpstreamActualChargeUsd(v)
	return _u
}

// ClearUpstreamActualChargeUsd clears the value of the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamActualChargeUsd() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamActualChargeUsd()
	return _u
}

// SetUpstreamStandardCharge sets the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamStandardCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.ResetUpstreamStandardCharge()
	_u.mutation.SetUpstreamStandardCharge(v)
	return _u
}

// SetNillableUpstreamStandardCharge sets the "upstream_standard_charge" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamStandardCharge(v *decimal.Decimal) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamStandardCharge(*v)
	}
	return _u
}

// AddUpstreamStandardCharge adds value to the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdate) AddUpstreamStandardCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdate {
	_u.mutation.AddUpstreamStandardCharge(v)
	return _u
}

// ClearUpstreamStandardCharge clears the value of the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamStandardCharge() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamStandardCharge()
	return _u
}

// SetUpstreamChargeCurrency sets the "upstream_charge_currency" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamChargeCurrency(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamChargeCurrency(v)
	return _u
}

// SetNillableUpstreamChargeCurrency sets the "upstream_charge_currency" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamChargeCurrency(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamChargeCurrency(*v)
	}
	return _u
}

// ClearUpstreamChargeCurrency clears the value of the "upstream_charge_currency" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamChargeCurrency() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamChargeCurrency()
	return _u
}

// SetUpstreamChargeUnitSemantics sets the "upstream_charge_unit_semantics" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamChargeUnitSemantics(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamChargeUnitSemantics(v)
	return _u
}

// SetNillableUpstreamChargeUnitSemantics sets the "upstream_charge_unit_semantics" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamChargeUnitSemantics(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamChargeUnitSemantics(*v)
	}
	return _u
}

// ClearUpstreamChargeUnitSemantics clears the value of the "upstream_charge_unit_semantics" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamChargeUnitSemantics() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamChargeUnitSemantics()
	return _u
}

// SetUpstreamBillingRequestID sets the "upstream_billing_request_id" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamBillingRequestID(v string) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamBillingRequestID(v)
	return _u
}

// SetNillableUpstreamBillingRequestID sets the "upstream_billing_request_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableUpstreamBillingRequestID(v *string) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetUpstreamBillingRequestID(*v)
	}
	return _u
}

// ClearUpstreamBillingRequestID clears the value of the "upstream_billing_request_id" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamBillingRequestID() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamBillingRequestID()
	return _u
}

// SetUpstreamChargeSnapshot sets the "upstream_charge_snapshot" field.
func (_u *UsageUpstreamAttemptUpdate) SetUpstreamChargeSnapshot(v map[string]interface{}) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetUpstreamChargeSnapshot(v)
	return _u
}

// ClearUpstreamChargeSnapshot clears the value of the "upstream_charge_snapshot" field.
func (_u *UsageUpstreamAttemptUpdate) ClearUpstreamChargeSnapshot() *UsageUpstreamAttemptUpdate {
	_u.mutation.ClearUpstreamChargeSnapshot()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *UsageUpstreamAttemptUpdate) SetCompletedAt(v time.Time) *UsageUpstreamAttemptUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdate) SetNillableCompletedAt(v *time.Time) *UsageUpstreamAttemptUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the UsageUpstreamAttemptMutation object of the builder.
func (_u *UsageUpstreamAttemptUpdate) Mutation() *UsageUpstreamAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageUpstreamAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageUpstreamAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageUpstreamAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageUpstreamAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageUpstreamAttemptUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usageupstreamattempt.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptNo(); ok {
		if err := usageupstreamattempt.AttemptNoValidator(v); err != nil {
			return &ValidationError{Name: "attempt_no", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.attempt_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := usageupstreamattempt.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := usageupstreamattempt.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := usageupstreamattempt.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := usageupstreamattempt.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheReadTokens(); ok {
		if err := usageupstreamattempt.CacheReadTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_read_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_read_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreationTokens(); ok {
		if err := usageupstreamattempt.CacheCreationTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreation5mTokens(); ok {
		if err := usageupstreamattempt.CacheCreation5mTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_5m_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_5m_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreation1hTokens(); ok {
		if err := usageupstreamattempt.CacheCreation1hTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_1h_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_1h_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestCount(); ok {
		if err := usageupstreamattempt.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.request_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageCount(); ok {
		if err := usageupstreamattempt.ImageCountValidator(v); err != nil {
			return &ValidationError{Name: "image_count", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.image_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoSeconds(); ok {
		if err := usageupstreamattempt.VideoSecondsValidator(v); err != nil {
			return &ValidationError{Name: "video_seconds", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.video_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		if err := usageupstreamattempt.UpstreamMultiplierSourceValidator(v); err != nil {
			return &ValidationError{Name: "upstream_multiplier_source", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_multiplier_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamChargeCurrency(); ok {
		if err := usageupstreamattempt.UpstreamChargeCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "upstream_charge_currency", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_charge_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamChargeUnitSemantics(); ok {
		if err := usageupstreamattempt.UpstreamChargeUnitSemanticsValidator(v); err != nil {
			return &ValidationError{Name: "upstream_charge_unit_semantics", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_charge_unit_semantics": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamBillingRequestID(); ok {
		if err := usageupstreamattempt.UpstreamBillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_billing_request_id", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_billing_request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageUpstreamAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usageupstreamattempt.Table, usageupstreamattempt.Columns, sqlgraph.NewFieldSpec(usageupstreamattempt.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usageupstreamattempt.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usageupstreamattempt.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptNo(); ok {
		_spec.SetField(usageupstreamattempt.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNo(); ok {
		_spec.AddField(usageupstreamattempt.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usageupstreamattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usageupstreamattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(usageupstreamattempt.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(usageupstreamattempt.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(usageupstreamattempt.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(usageupstreamattempt.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreation5mTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreation5mTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreation5mTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreation5mTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreation1hTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreation1hTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreation1hTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreation1hTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageupstreamattempt.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageupstreamattempt.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(usageupstreamattempt.FieldImageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(usageupstreamattempt.FieldImageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VideoSeconds(); ok {
		_spec.SetField(usageupstreamattempt.FieldVideoSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVideoSeconds(); ok {
		_spec.AddField(usageupstreamattempt.FieldVideoSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamCostMultiplier(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamCostMultiplier(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamCostMultiplierCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierChangeID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamMultiplierChangeID(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamMultiplierChangeIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierSource, field.TypeString, value)
	}
	if _u.mutation.UpstreamMultiplierSourceCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamMultiplierEffectiveAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamMultiplierEffectiveAtCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccountFinanceProfileID(); ok {
		_spec.SetField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountFinanceProfileID(); ok {
		_spec.AddField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if _u.mutation.AccountFinanceProfileIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Billable(); ok {
		_spec.SetField(usageupstreamattempt.FieldBillable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BillingObservedAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldBillingObservedAt, field.TypeTime, value)
	}
	if _u.mutation.BillingObservedAtCleared() {
		_spec.ClearField(usageupstreamattempt.FieldBillingObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpstreamActualCharge(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamActualCharge(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamActualChargeCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamActualChargeUsd(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamActualChargeUsd(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamActualChargeUsdCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamStandardCharge(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStandardCharge(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamStandardChargeCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamChargeCurrency(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeCurrency, field.TypeString, value)
	}
	if _u.mutation.UpstreamChargeCurrencyCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamChargeUnitSemantics(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeUnitSemantics, field.TypeString, value)
	}
	if _u.mutation.UpstreamChargeUnitSemanticsCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeUnitSemantics, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamBillingRequestID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamBillingRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamBillingRequestIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamBillingRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamChargeSnapshot(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamChargeSnapshotCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldCompletedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageupstreamattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageUpstreamAttemptUpdateOne is the builder for updating a single UsageUpstreamAttempt entity.
type UsageUpstreamAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageUpstreamAttemptMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUsageLogID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUsageLogID(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUsageLogID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetRequestID(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableRequestID(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAttemptNo sets the "attempt_no" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetAttemptNo(v int) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetAttemptNo()
	_u.mutation.SetAttemptNo(v)
	return _u
}

// SetNillableAttemptNo sets the "attempt_no" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableAttemptNo(v *int) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetAttemptNo(*v)
	}
	return _u
}

// AddAttemptNo adds value to the "attempt_no" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddAttemptNo(v int) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddAttemptNo(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetAccountID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableAccountID(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddAccountID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetChannelID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableChannelID(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddChannelID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearChannelID() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamModel(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamModel(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetServiceTier(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableServiceTier(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearServiceTier() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetInputTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableInputTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddInputTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetOutputTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableOutputTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddOutputTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetCacheReadTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableCacheReadTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddCacheReadTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetCacheCreationTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableCacheCreationTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddCacheCreationTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetCacheCreation5mTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetCacheCreation5mTokens()
	_u.mutation.SetCacheCreation5mTokens(v)
	return _u
}

// SetNillableCacheCreation5mTokens sets the "cache_creation_5m_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableCacheCreation5mTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetCacheCreation5mTokens(*v)
	}
	return _u
}

// AddCacheCreation5mTokens adds value to the "cache_creation_5m_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddCacheCreation5mTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddCacheCreation5mTokens(v)
	return _u
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetCacheCreation1hTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetCacheCreation1hTokens()
	_u.mutation.SetCacheCreation1hTokens(v)
	return _u
}

// SetNillableCacheCreation1hTokens sets the "cache_creation_1h_tokens" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableCacheCreation1hTokens(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetCacheCreation1hTokens(*v)
	}
	return _u
}

// AddCacheCreation1hTokens adds value to the "cache_creation_1h_tokens" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddCacheCreation1hTokens(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddCacheCreation1hTokens(v)
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetRequestCount(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableRequestCount(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddRequestCount(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetImageCount sets the "image_count" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetImageCount(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetImageCount()
	_u.mutation.SetImageCount(v)
	return _u
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableImageCount(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetImageCount(*v)
	}
	return _u
}

// AddImageCount adds value to the "image_count" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddImageCount(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddImageCount(v)
	return _u
}

// SetVideoSeconds sets the "video_seconds" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetVideoSeconds(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetVideoSeconds()
	_u.mutation.SetVideoSeconds(v)
	return _u
}

// SetNillableVideoSeconds sets the "video_seconds" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableVideoSeconds(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetVideoSeconds(*v)
	}
	return _u
}

// AddVideoSeconds adds value to the "video_seconds" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddVideoSeconds(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddVideoSeconds(v)
	return _u
}

// SetUpstreamCostMultiplier sets the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamCostMultiplier(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUpstreamCostMultiplier()
	_u.mutation.SetUpstreamCostMultiplier(v)
	return _u
}

// SetNillableUpstreamCostMultiplier sets the "upstream_cost_multiplier" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamCostMultiplier(v *decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamCostMultiplier(*v)
	}
	return _u
}

// AddUpstreamCostMultiplier adds value to the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUpstreamCostMultiplier(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUpstreamCostMultiplier(v)
	return _u
}

// ClearUpstreamCostMultiplier clears the value of the "upstream_cost_multiplier" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamCostMultiplier() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamCostMultiplier()
	return _u
}

// SetUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamMultiplierChangeID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUpstreamMultiplierChangeID()
	_u.mutation.SetUpstreamMultiplierChangeID(v)
	return _u
}

// SetNillableUpstreamMultiplierChangeID sets the "upstream_multiplier_change_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamMultiplierChangeID(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierChangeID(*v)
	}
	return _u
}

// AddUpstreamMultiplierChangeID adds value to the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUpstreamMultiplierChangeID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUpstreamMultiplierChangeID(v)
	return _u
}

// ClearUpstreamMultiplierChangeID clears the value of the "upstream_multiplier_change_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamMultiplierChangeID() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamMultiplierChangeID()
	return _u
}

// SetUpstreamMultiplierSource sets the "upstream_multiplier_source" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamMultiplierSource(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamMultiplierSource(v)
	return _u
}

// SetNillableUpstreamMultiplierSource sets the "upstream_multiplier_source" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamMultiplierSource(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierSource(*v)
	}
	return _u
}

// ClearUpstreamMultiplierSource clears the value of the "upstream_multiplier_source" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamMultiplierSource() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamMultiplierSource()
	return _u
}

// SetUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamMultiplierEffectiveAt(v time.Time) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamMultiplierEffectiveAt(v)
	return _u
}

// SetNillableUpstreamMultiplierEffectiveAt sets the "upstream_multiplier_effective_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamMultiplierEffectiveAt(v *time.Time) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamMultiplierEffectiveAt(*v)
	}
	return _u
}

// ClearUpstreamMultiplierEffectiveAt clears the value of the "upstream_multiplier_effective_at" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamMultiplierEffectiveAt() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamMultiplierEffectiveAt()
	return _u
}

// SetAccountFinanceProfileID sets the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetAccountFinanceProfileID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetAccountFinanceProfileID()
	_u.mutation.SetAccountFinanceProfileID(v)
	return _u
}

// SetNillableAccountFinanceProfileID sets the "account_finance_profile_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableAccountFinanceProfileID(v *int64) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetAccountFinanceProfileID(*v)
	}
	return _u
}

// AddAccountFinanceProfileID adds value to the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddAccountFinanceProfileID(v int64) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddAccountFinanceProfileID(v)
	return _u
}

// ClearAccountFinanceProfileID clears the value of the "account_finance_profile_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearAccountFinanceProfileID() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearAccountFinanceProfileID()
	return _u
}

// SetBillable sets the "billable" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetBillable(v bool) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetBillable(v)
	return _u
}

// SetNillableBillable sets the "billable" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableBillable(v *bool) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetBillable(*v)
	}
	return _u
}

// SetBillingObservedAt sets the "billing_observed_at" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetBillingObservedAt(v time.Time) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetBillingObservedAt(v)
	return _u
}

// SetNillableBillingObservedAt sets the "billing_observed_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableBillingObservedAt(v *time.Time) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetBillingObservedAt(*v)
	}
	return _u
}

// ClearBillingObservedAt clears the value of the "billing_observed_at" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearBillingObservedAt() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearBillingObservedAt()
	return _u
}

// SetUpstreamActualCharge sets the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamActualCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUpstreamActualCharge()
	_u.mutation.SetUpstreamActualCharge(v)
	return _u
}

// SetNillableUpstreamActualCharge sets the "upstream_actual_charge" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamActualCharge(v *decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamActualCharge(*v)
	}
	return _u
}

// AddUpstreamActualCharge adds value to the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUpstreamActualCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUpstreamActualCharge(v)
	return _u
}

// ClearUpstreamActualCharge clears the value of the "upstream_actual_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamActualCharge() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamActualCharge()
	return _u
}

// SetUpstreamActualChargeUsd sets the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamActualChargeUsd(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUpstreamActualChargeUsd()
	_u.mutation.SetUpstreamActualChargeUsd(v)
	return _u
}

// SetNillableUpstreamActualChargeUsd sets the "upstream_actual_charge_usd" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamActualChargeUsd(v *decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamActualChargeUsd(*v)
	}
	return _u
}

// AddUpstreamActualChargeUsd adds value to the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUpstreamActualChargeUsd(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUpstreamActualChargeUsd(v)
	return _u
}

// ClearUpstreamActualChargeUsd clears the value of the "upstream_actual_charge_usd" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamActualChargeUsd() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamActualChargeUsd()
	return _u
}

// SetUpstreamStandardCharge sets the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamStandardCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ResetUpstreamStandardCharge()
	_u.mutation.SetUpstreamStandardCharge(v)
	return _u
}

// SetNillableUpstreamStandardCharge sets the "upstream_standard_charge" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamStandardCharge(v *decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamStandardCharge(*v)
	}
	return _u
}

// AddUpstreamStandardCharge adds value to the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) AddUpstreamStandardCharge(v decimal.Decimal) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.AddUpstreamStandardCharge(v)
	return _u
}

// ClearUpstreamStandardCharge clears the value of the "upstream_standard_charge" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamStandardCharge() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamStandardCharge()
	return _u
}

// SetUpstreamChargeCurrency sets the "upstream_charge_currency" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamChargeCurrency(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamChargeCurrency(v)
	return _u
}

// SetNillableUpstreamChargeCurrency sets the "upstream_charge_currency" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamChargeCurrency(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamChargeCurrency(*v)
	}
	return _u
}

// ClearUpstreamChargeCurrency clears the value of the "upstream_charge_currency" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamChargeCurrency() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamChargeCurrency()
	return _u
}

// SetUpstreamChargeUnitSemantics sets the "upstream_charge_unit_semantics" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamChargeUnitSemantics(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamChargeUnitSemantics(v)
	return _u
}

// SetNillableUpstreamChargeUnitSemantics sets the "upstream_charge_unit_semantics" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamChargeUnitSemantics(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamChargeUnitSemantics(*v)
	}
	return _u
}

// ClearUpstreamChargeUnitSemantics clears the value of the "upstream_charge_unit_semantics" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamChargeUnitSemantics() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamChargeUnitSemantics()
	return _u
}

// SetUpstreamBillingRequestID sets the "upstream_billing_request_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamBillingRequestID(v string) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamBillingRequestID(v)
	return _u
}

// SetNillableUpstreamBillingRequestID sets the "upstream_billing_request_id" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableUpstreamBillingRequestID(v *string) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamBillingRequestID(*v)
	}
	return _u
}

// ClearUpstreamBillingRequestID clears the value of the "upstream_billing_request_id" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamBillingRequestID() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamBillingRequestID()
	return _u
}

// SetUpstreamChargeSnapshot sets the "upstream_charge_snapshot" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetUpstreamChargeSnapshot(v map[string]interface{}) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetUpstreamChargeSnapshot(v)
	return _u
}

// ClearUpstreamChargeSnapshot clears the value of the "upstream_charge_snapshot" field.
func (_u *UsageUpstreamAttemptUpdateOne) ClearUpstreamChargeSnapshot() *UsageUpstreamAttemptUpdateOne {
	_u.mutation.ClearUpstreamChargeSnapshot()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *UsageUpstreamAttemptUpdateOne) SetCompletedAt(v time.Time) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *UsageUpstreamAttemptUpdateOne) SetNillableCompletedAt(v *time.Time) *UsageUpstreamAttemptUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// Mutation returns the UsageUpstreamAttemptMutation object of the builder.
func (_u *UsageUpstreamAttemptUpdateOne) Mutation() *UsageUpstreamAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageUpstreamAttemptUpdate builder.
func (_u *UsageUpstreamAttemptUpdateOne) Where(ps ...predicate.UsageUpstreamAttempt) *UsageUpstreamAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageUpstreamAttemptUpdateOne) Select(field string, fields ...string) *UsageUpstreamAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageUpstreamAttempt entity.
func (_u *UsageUpstreamAttemptUpdateOne) Save(ctx context.Context) (*UsageUpstreamAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageUpstreamAttemptUpdateOne) SaveX(ctx context.Context) *UsageUpstreamAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageUpstreamAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageUpstreamAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageUpstreamAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := usageupstreamattempt.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptNo(); ok {
		if err := usageupstreamattempt.AttemptNoValidator(v); err != nil {
			return &ValidationError{Name: "attempt_no", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.attempt_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := usageupstreamattempt.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := usageupstreamattempt.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := usageupstreamattempt.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := usageupstreamattempt.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheReadTokens(); ok {
		if err := usageupstreamattempt.CacheReadTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_read_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_read_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreationTokens(); ok {
		if err := usageupstreamattempt.CacheCreationTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreation5mTokens(); ok {
		if err := usageupstreamattempt.CacheCreation5mTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_5m_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_5m_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheCreation1hTokens(); ok {
		if err := usageupstreamattempt.CacheCreation1hTokensValidator(v); err != nil {
			return &ValidationError{Name: "cache_creation_1h_tokens", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.cache_creation_1h_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestCount(); ok {
		if err := usageupstreamattempt.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.request_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageCount(); ok {
		if err := usageupstreamattempt.ImageCountValidator(v); err != nil {
			return &ValidationError{Name: "image_count", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.image_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoSeconds(); ok {
		if err := usageupstreamattempt.VideoSecondsValidator(v); err != nil {
			return &ValidationError{Name: "video_seconds", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.video_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		if err := usageupstreamattempt.UpstreamMultiplierSourceValidator(v); err != nil {
			return &ValidationError{Name: "upstream_multiplier_source", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_multiplier_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamChargeCurrency(); ok {
		if err := usageupstreamattempt.UpstreamChargeCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "upstream_charge_currency", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_charge_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamChargeUnitSemantics(); ok {
		if err := usageupstreamattempt.UpstreamChargeUnitSemanticsValidator(v); err != nil {
			return &ValidationError{Name: "upstream_charge_unit_semantics", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_charge_unit_semantics": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamBillingRequestID(); ok {
		if err := usageupstreamattempt.UpstreamBillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_billing_request_id", err: fmt.Errorf(`ent: validator failed for field "UsageUpstreamAttempt.upstream_billing_request_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageUpstreamAttemptUpdateOne) sqlSave(ctx context.Context) (_node *UsageUpstreamAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usageupstreamattempt.Table, usageupstreamattempt.Columns, sqlgraph.NewFieldSpec(usageupstreamattempt.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageUpstreamAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usageupstreamattempt.FieldID)
		for _, f := range fields {
			if !usageupstreamattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usageupstreamattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(usageupstreamattempt.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(usageupstreamattempt.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptNo(); ok {
		_spec.SetField(usageupstreamattempt.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNo(); ok {
		_spec.AddField(usageupstreamattempt.FieldAttemptNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(usageupstreamattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(usageupstreamattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(usageupstreamattempt.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(usageupstreamattempt.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(usageupstreamattempt.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(usageupstreamattempt.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreation5mTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreation5mTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreation5mTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreation5mTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreation1hTokens(); ok {
		_spec.SetField(usageupstreamattempt.FieldCacheCreation1hTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreation1hTokens(); ok {
		_spec.AddField(usageupstreamattempt.FieldCacheCreation1hTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(usageupstreamattempt.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(usageupstreamattempt.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ImageCount(); ok {
		_spec.SetField(usageupstreamattempt.FieldImageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageCount(); ok {
		_spec.AddField(usageupstreamattempt.FieldImageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VideoSeconds(); ok {
		_spec.SetField(usageupstreamattempt.FieldVideoSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVideoSeconds(); ok {
		_spec.AddField(usageupstreamattempt.FieldVideoSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamCostMultiplier(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamCostMultiplier(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamCostMultiplierCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamCostMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierChangeID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamMultiplierChangeID(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamMultiplierChangeIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierChangeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpstreamMultiplierSource(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierSource, field.TypeString, value)
	}
	if _u.mutation.UpstreamMultiplierSourceCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierSource, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamMultiplierEffectiveAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamMultiplierEffectiveAtCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamMultiplierEffectiveAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccountFinanceProfileID(); ok {
		_spec.SetField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountFinanceProfileID(); ok {
		_spec.AddField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64, value)
	}
	if _u.mutation.AccountFinanceProfileIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldAccountFinanceProfileID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Billable(); ok {
		_spec.SetField(usageupstreamattempt.FieldBillable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BillingObservedAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldBillingObservedAt, field.TypeTime, value)
	}
	if _u.mutation.BillingObservedAtCleared() {
		_spec.ClearField(usageupstreamattempt.FieldBillingObservedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpstreamActualCharge(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamActualCharge(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamActualChargeCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamActualCharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamActualChargeUsd(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamActualChargeUsd(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamActualChargeUsdCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamActualChargeUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamStandardCharge(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStandardCharge(); ok {
		_spec.AddField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64, value)
	}
	if _u.mutation.UpstreamStandardChargeCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamStandardCharge, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamChargeCurrency(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeCurrency, field.TypeString, value)
	}
	if _u.mutation.UpstreamChargeCurrencyCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamChargeUnitSemantics(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeUnitSemantics, field.TypeString, value)
	}
	if _u.mutation.UpstreamChargeUnitSemanticsCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeUnitSemantics, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamBillingRequestID(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamBillingRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamBillingRequestIDCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamBillingRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamChargeSnapshot(); ok {
		_spec.SetField(usageupstreamattempt.FieldUpstreamChargeSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamChargeSnapshotCleared() {
		_spec.ClearField(usageupstreamattempt.FieldUpstreamChargeSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(usageupstreamattempt.FieldCompletedAt, field.TypeTime, value)
	}
	_node = &UsageUpstreamAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usageupstreamattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
