import { beforeEach, describe, expect, it, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import { defineComponent, h } from 'vue'
import SettingsView from '../SettingsView.vue'

const getSettings = vi.fn(); const updateSettings = vi.fn(); const getXSearchPrice = vi.fn(); const updateXSearchPrice = vi.fn()
vi.mock('@/api', () => ({ adminAPI: { settings: new Proxy({}, { get: (_t, key) => ({ getSettings, updateSettings, getXSearchPrice, updateXSearchPrice } as Record<string, unknown>)[String(key)] ?? vi.fn().mockResolvedValue({}) }), groups: { getAll: vi.fn().mockResolvedValue([]) }, proxies: { list: vi.fn().mockResolvedValue([]) }, users: { getById: vi.fn(), list: vi.fn().mockResolvedValue([]) }, payment: { getProviders: vi.fn().mockResolvedValue([]), updateProvider: vi.fn(), createProvider: vi.fn(), deleteProvider: vi.fn() } } }))
vi.mock('@/stores', () => ({ useAppStore: () => ({ showError: vi.fn(), showSuccess: vi.fn(), showWarning: vi.fn(), showInfo: vi.fn(), fetchPublicSettings: vi.fn() }) })); vi.mock('@/stores/adminSettings', () => ({ useAdminSettingsStore: () => ({ fetch: vi.fn() }) })); vi.mock('@/composables/useClipboard', () => ({ useClipboard: () => ({ copyToClipboard: vi.fn() }) })); vi.mock('@/utils/apiError', () => ({ extractApiErrorMessage: () => 'error' })); vi.mock('vue-i18n', async (importOriginal) => ({ ...(await importOriginal()), useI18n: () => ({ t: (key: string) => key, locale: { value: 'zh-CN' } }) }))
const Toggle = defineComponent({ props: { modelValue: Boolean }, emits: ['update:modelValue'], setup(props, { emit, attrs }) { return () => h('input', { ...attrs, type: 'checkbox', checked: props.modelValue, onChange: (e: Event) => emit('update:modelValue', (e.target as HTMLInputElement).checked) }) } })
const stubs = { AppLayout: { template: '<div><slot /></div>' }, Toggle, Select: true, Icon: true, ConfirmDialog: true, PaymentProviderList: true, PaymentProviderDialog: true, GroupBadge: true, GroupOptionItem: true, ProxySelector: true, ImageUpload: true, BackupSettings: true }
describe('SettingsView X Search price', () => { beforeEach(() => { getSettings.mockReset().mockResolvedValue({}); updateSettings.mockReset().mockResolvedValue({}); getXSearchPrice.mockReset().mockResolvedValue({ price_per_request: '0.0025' }); updateXSearchPrice.mockReset().mockImplementation(async (price: string) => ({ price_per_request: price })) })
  it('loads and saves the X Search price', async () => { const wrapper = mount(SettingsView, { global: { stubs } }); await new Promise((resolve) => setTimeout(resolve, 0)); const input = wrapper.find('input[placeholder="0.0010000000"]'); expect((input.element as HTMLInputElement).value).toBe('0.0025'); await input.setValue('0.0030'); await wrapper.find('form').trigger('submit'); expect(updateXSearchPrice).toHaveBeenCalledWith('0.0030') })
})
